/**
 * Every mounted route, classified for property scoping.
 *
 * `src/__tests__/route-coverage.test.ts` fails when a route is missing here, so
 * adding an endpoint forces the question "does this need property scoping?" to
 * be answered rather than skipped — which is how 29 of 37 route files ended up
 * unscoped in the first place.
 *
 *   { scoped: "<how>" }  the handler restricts rows to the caller's property
 *   { exempt: "<why>" }  a deliberate decision not to, with the reason
 *
 * Entries whose reason starts "NOT YET SCOPED" are the live burn-down list.
 * Shrinking it is the work; the test stops it growing silently.
 *
 * Generated from the live express stack, then reasons written by hand. Keys are
 * `<file> METHOD /relative/path`: Express 5 replaced each layer's `regexp` with
 * opaque `matchers`, so a mount prefix can no longer be recovered from the
 * stack, and the file name is stable, unique and points at the handler.
 */
export type ScopeClass = { scoped: string } | { exempt: string };

/** Routes with no tagged authz gate, each justified. */
export const PUBLIC_ROUTES: Record<string, string> = {
  'employees POST /check-in': "the caller's OWN attendance — resolved from their email, cannot write another employee's row",
  'employees POST /check-out': "the caller's OWN attendance — resolved from their email, cannot write another employee's row",
  'audit-reports GET /:token': 'expiring report share link; the token IS the credential',
  'auth GET /me': 'pre-authentication by definition (login / OTP / password reset / refresh)',
  'auth POST /forgot-password': 'pre-authentication by definition (login / OTP / password reset / refresh)',
  'auth POST /forgot-password/verify': 'pre-authentication by definition (login / OTP / password reset / refresh)',
  'auth POST /forgot-username': 'pre-authentication by definition (login / OTP / password reset / refresh)',
  'auth POST /forgot-username/verify': 'pre-authentication by definition (login / OTP / password reset / refresh)',
  'auth POST /login': 'pre-authentication by definition (login / OTP / password reset / refresh)',
  'auth POST /logout': 'pre-authentication by definition (login / OTP / password reset / refresh)',
  'auth POST /recover-username': 'pre-authentication by definition (login / OTP / password reset / refresh)',
  'auth POST /refresh': 'pre-authentication by definition (login / OTP / password reset / refresh)',
  'auth POST /resend-otp': 'pre-authentication by definition (login / OTP / password reset / refresh)',
  'auth POST /reset-password': 'pre-authentication by definition (login / OTP / password reset / refresh)',
  'auth POST /verify-otp': 'pre-authentication by definition (login / OTP / password reset / refresh)',
  'auth-google GET /config': 'OAuth handshake — the provider calls these unauthenticated',
  'auth-google GET /google': 'OAuth handshake — the provider calls these unauthenticated',
  'auth-google GET /google/callback': 'OAuth handshake — the provider calls these unauthenticated',
  'bulk POST /:resource': 'authorize() chosen at RUNTIME per :resource, so no static tag',
  'food-ops GET /guests/export.csv': 'gated by the legacy requireRoles() from auth.ts — retire with ROLE_RANK',
  'food-ops GET /guests/export.pdf': 'gated by the legacy requireRoles() from auth.ts — retire with ROLE_RANK',
  'food-ops GET /guests/export.xls': 'gated by the legacy requireRoles() from auth.ts — retire with ROLE_RANK',
  'food-ops GET /menu/shared/:token': 'expiring share link; the token IS the credential',
  'food-ops GET /reports/export': 'gated by the legacy requireRoles() from auth.ts — retire with ROLE_RANK',
  'food-ops GET /reports/export.:fmt': 'gated by the legacy requireRoles() from auth.ts — retire with ROLE_RANK',
  'food-ops GET /waste-analytics/export.:fmt': 'gated by the legacy requireRoles() from auth.ts — retire with ROLE_RANK',
  'food-ops PUT /settings/ontime-tolerance': 'gated inline on isSuperAdmin (stricter than any module gate)',
  'food-ops PUT /settings/order-headroom': 'gated inline on isSuperAdmin (stricter than any module gate)',
  'food-ops PUT /system-config/food-defaults': 'gated inline on isSuperAdmin (stricter than any module gate)',
  'form-drafts DELETE /': "the caller's OWN drafts — self-scoped by userId in the handler",
  'form-drafts GET /': "the caller's OWN drafts — self-scoped by userId in the handler",
  'form-drafts GET /all': "the caller's OWN drafts — self-scoped by userId in the handler",
  'form-drafts PUT /': "the caller's OWN drafts — self-scoped by userId in the handler",
  'geocode GET /forward': 'authenticated proxy to a geocoding provider; no tenant data',
  'geocode GET /reverse': 'authenticated proxy to a geocoding provider; no tenant data',
  'health GET /healthz': 'liveness / readiness probe',
  'health GET /readyz': 'liveness / readiness probe',
  'kyc-esign GET /kyc/digilocker/callback': 'token-bearing resident flow / provider callback',
  'kyc-esign GET /sign/:token': 'token-bearing resident flow / provider callback',
  'kyc-esign POST /sign/:token': 'token-bearing resident flow / provider callback',
  'notifications DELETE /suppressions': 'gated inline on isSuperAdmin (stricter than any module gate)',
  'notifications GET /': "the caller's own notifications — self-scoped by userId",
  'notifications GET /stream': "the caller's own notifications — self-scoped by userId",
  'notifications GET /suppressions': 'gated inline on isSuperAdmin (stricter than any module gate)',
  'notifications PATCH /:id/read': "the caller's own notifications — self-scoped by userId",
  'notifications PATCH /read-all': "the caller's own notifications — self-scoped by userId",
  'operations POST /ingest': 'IoT device ingest, authenticated by device token',
  'push GET /vapid-public-key': 'per-user push subscription; the subject is the caller',
  'push POST /subscribe': 'per-user push subscription; the subject is the caller',
  'push POST /unsubscribe': 'per-user push subscription; the subject is the caller',
  'settings GET /otp-config': 'gated inline on isSuperAdmin (stricter than any module gate)',
  'settings PUT /otp-config': 'gated inline on isSuperAdmin (stricter than any module gate)',
  'webhooks POST /webhooks/razorpay': 'provider callback, authenticated by signature verification not by session',
  'webhooks POST /webhooks/ses': 'provider callback, authenticated by signature verification not by session',
};

export const ROUTE_SCOPE: Record<string, ScopeClass> = {
  'employees POST /:id/approve': { scoped: 'assertEmployeeInScope + enforceSod (requester may not approve)' },
  'employees POST /:id/correction': { scoped: 'assertEmployeeInScope on the attendance row' },
  'access GET /assignments/:userId': { exempt: 'admin console; ACCESS_CONTROL gate + the grant guards on write' },
  'access POST /grants': { exempt: 'admin console; assertGrantIsSafe enforces node scope per request' },
  'access POST /grants/:id/restore': { exempt: 'admin console; re-runs the full grant guard set' },
  'access POST /grants/:id/revoke': { exempt: 'admin console; ACCESS_CONTROL:configure + mandatory reason' },
  'access PUT /assignments/:userId': { exempt: 'admin console; assertGrantIsSafe per node + mandatory reason' },
  'activity GET /': { scoped: 'propertyScope OR org-wide rows (scopedPropertyId)' },
  'activity GET /facets': { exempt: 'filter vocabulary from the code registry; no tenant data' },
  'activity GET /verify': { exempt: 'chain integrity for one stream; returns counts, not rows' },
  'access GET /matrix': { exempt: 'admin console; gated on ACCESS_CONTROL which only the parity roles hold' },
  'access GET /roles': { exempt: 'admin console; gated on ACCESS_CONTROL which only the parity roles hold' },
  'access POST /roles': { exempt: 'admin console; ACCESS_CONTROL:configure + rank and amplification guards' },
  'access PUT /matrix': { exempt: 'admin console; ACCESS_CONTROL:configure + full guard set in matrix-guards.ts' },
  'access GET /grants': { exempt: 'admin console; gated on ACCESS_CONTROL which only the parity roles hold' },
  'access GET /overrides/:userId': { exempt: 'admin console; gated on ACCESS_CONTROL which only the parity roles hold' },
  'access PUT /overrides/:userId': { exempt: 'admin console; ACCESS_CONTROL:configure + assertOverrideIsSafe (self, rank, ceiling, protected modules)' },
  'access GET /clone-access/:fromUserId/:toUserId': { exempt: 'admin console; dry run only, writes nothing' },
  'access POST /clone-access': { exempt: 'admin console; re-runs the grant and override guard sets per copied row' },
  'access GET /manifest': { exempt: 'admin console; gated on ACCESS_CONTROL which only the parity roles hold' },
  'access GET /nodes': { exempt: 'admin console; gated on ACCESS_CONTROL which only the parity roles hold' },
  'access GET /preview/:userId': { exempt: 'admin console; gated on ACCESS_CONTROL which only the parity roles hold' },
  'access GET /users': { exempt: 'admin console; gated on ACCESS_CONTROL which only the parity roles hold' },
  'audit-admin GET /grants': { scoped: 'grant guards: no self-grant, GLOBAL is parity-only, assertCanAssignRole' },
  'audit-admin GET /org-nodes': { scoped: 'grant guards: no self-grant, GLOBAL is parity-only, assertCanAssignRole' },
  'audit-admin GET /performance-bands': { scoped: 'grant guards: no self-grant, GLOBAL is parity-only, assertCanAssignRole' },
  'audit-admin GET /rating-scales': { scoped: 'grant guards: no self-grant, GLOBAL is parity-only, assertCanAssignRole' },
  'audit-admin GET /settings': { scoped: 'grant guards: no self-grant, GLOBAL is parity-only, assertCanAssignRole' },
  'audit-admin POST /grants': { scoped: 'grant guards: no self-grant, GLOBAL is parity-only, assertCanAssignRole' },
  'audit-admin POST /grants/:id/revoke': { scoped: 'grant guards: no self-grant, GLOBAL is parity-only, assertCanAssignRole' },
  'audit-admin POST /rating-scales': { scoped: 'grant guards: no self-grant, GLOBAL is parity-only, assertCanAssignRole' },
  'audit-admin PUT /performance-bands': { scoped: 'grant guards: no self-grant, GLOBAL is parity-only, assertCanAssignRole' },
  'audit-admin PUT /rating-scales/:id': { scoped: 'grant guards: no self-grant, GLOBAL is parity-only, assertCanAssignRole' },
  'audit-admin PUT /settings/:key': { scoped: 'grant guards: no self-grant, GLOBAL is parity-only, assertCanAssignRole' },
  'audit-reports DELETE /:id/shares/:sid': { scoped: 'resolveAuditAccess' },
  'audit-reports GET /': { scoped: 'resolveAuditAccess' },
  'audit-reports GET /:id': { scoped: 'resolveAuditAccess' },
  'audit-reports GET /dashboard/summary': { scoped: 'resolveAuditAccess' },
  'audit-reports GET /filter-properties': { scoped: 'resolveAuditAccess' },
  'audit-reports GET /named/:key': { scoped: 'resolveAuditAccess' },
  'audit-reports POST /:id/generate': { scoped: 'resolveAuditAccess' },
  'audit-reports POST /:id/shares': { scoped: 'resolveAuditAccess' },
  'audit-reviews GET /:id/workspace': { scoped: 'resolveAuditAccess on the queue; loadAudit() scope-checks every action' },
  'audit-reviews GET /queue': { scoped: 'resolveAuditAccess on the queue; loadAudit() scope-checks every action' },
  'audit-reviews POST /:id/approve': { scoped: 'resolveAuditAccess on the queue; loadAudit() scope-checks every action' },
  'audit-reviews POST /:id/reject': { scoped: 'resolveAuditAccess on the queue; loadAudit() scope-checks every action' },
  'audit-reviews POST /:id/reopen': { scoped: 'resolveAuditAccess on the queue; loadAudit() scope-checks every action' },
  'audit-schedules GET /': { scoped: 'visibleAuditTypes(access) restricts the schedule list' },
  'audit-schedules GET /:id': { scoped: 'visibleAuditTypes(access) restricts the schedule list' },
  'audit-schedules GET /view/calendar': { scoped: 'visibleAuditTypes(access) restricts the schedule list' },
  'audit-schedules GET /view/scope-options': { scoped: 'visibleAuditTypes(access) restricts the schedule list' },
  'audit-schedules PATCH /:id': { scoped: 'visibleAuditTypes(access) restricts the schedule list' },
  'audit-schedules POST /': { scoped: 'visibleAuditTypes(access) restricts the schedule list' },
  'audit-schedules POST /:id/end': { scoped: 'visibleAuditTypes(access) restricts the schedule list' },
  'audit-schedules POST /:id/occurrences/restore': { scoped: 'visibleAuditTypes(access) restricts the schedule list' },
  'audit-schedules POST /:id/occurrences/skip': { scoped: 'visibleAuditTypes(access) restricts the schedule list' },
  'audit-schedules POST /:id/pause': { scoped: 'visibleAuditTypes(access) restricts the schedule list' },
  'audit-schedules POST /:id/resume': { scoped: 'visibleAuditTypes(access) restricts the schedule list' },
  'audit-schedules POST /:id/split': { scoped: 'visibleAuditTypes(access) restricts the schedule list' },
  'audit-templates DELETE /questions/:qid': { exempt: 'org-wide template library — no property dimension' },
  'audit-templates DELETE /sections/:sid': { exempt: 'org-wide template library — no property dimension' },
  'audit-templates GET /': { exempt: 'org-wide template library — no property dimension' },
  'audit-templates GET /:id': { exempt: 'org-wide template library — no property dimension' },
  'audit-templates GET /check-duplicate': { exempt: 'org-wide template library — no property dimension' },
  'audit-templates GET /tags': { exempt: 'org-wide template library — no property dimension' },
  'audit-templates GET /versions/:vid': { exempt: 'org-wide template library — no property dimension' },
  'audit-templates GET /versions/:vid/where-used': { exempt: 'org-wide template library — no property dimension' },
  'audit-templates PATCH /:id': { exempt: 'org-wide template library — no property dimension' },
  'audit-templates PATCH /questions/:qid': { exempt: 'org-wide template library — no property dimension' },
  'audit-templates PATCH /sections/:sid': { exempt: 'org-wide template library — no property dimension' },
  'audit-templates PATCH /versions/:vid': { exempt: 'org-wide template library — no property dimension' },
  'audit-templates POST /': { exempt: 'org-wide template library — no property dimension' },
  'audit-templates POST /:id/archive': { exempt: 'org-wide template library — no property dimension' },
  'audit-templates POST /:id/versions': { exempt: 'org-wide template library — no property dimension' },
  'audit-templates POST /sections': { exempt: 'org-wide template library — no property dimension' },
  'audit-templates POST /sections/:sid/questions': { exempt: 'org-wide template library — no property dimension' },
  'audit-templates POST /sections/:sid/questions/reorder': { exempt: 'org-wide template library — no property dimension' },
  'audit-templates POST /sections/reorder': { exempt: 'org-wide template library — no property dimension' },
  'audit-templates POST /versions/:vid/archive': { exempt: 'org-wide template library — no property dimension' },
  'audit-templates POST /versions/:vid/deprecate': { exempt: 'org-wide template library — no property dimension' },
  'audit-templates POST /versions/:vid/migrate-schedules': { exempt: 'org-wide template library — no property dimension' },
  'audit-templates POST /versions/:vid/publish': { exempt: 'org-wide template library — no property dimension' },
  'audits DELETE /:id/evidence/:eid': { scoped: 'resolveAuditAccess' },
  'audits GET /': { scoped: 'resolveAuditAccess' },
  'audits GET /:id': { scoped: 'resolveAuditAccess' },
  'audits GET /:id/events': { scoped: 'resolveAuditAccess' },
  'audits GET /:id/run': { scoped: 'resolveAuditAccess' },
  'audits GET /:id/submit-check': { scoped: 'resolveAuditAccess' },
  'audits GET /conductable-templates': { scoped: 'resolveAuditAccess' },
  'audits GET /my': { scoped: 'resolveAuditAccess' },
  'audits GET /target-properties': { scoped: 'resolveAuditAccess' },
  'audits GET /target-rooms': { scoped: 'resolveAuditAccess' },
  'audits GET /template-version/:vid': { scoped: 'resolveAuditAccess' },
  'audits GET /visible-types': { scoped: 'resolveAuditAccess' },
  'audits PATCH /:id': { scoped: 'resolveAuditAccess' },
  'audits POST /': { scoped: 'resolveAuditAccess' },
  'audits POST /:id/evidence': { scoped: 'resolveAuditAccess' },
  'audits POST /:id/start': { scoped: 'resolveAuditAccess' },
  'audits POST /:id/submit': { scoped: 'resolveAuditAccess' },
  'audits POST /reassign': { scoped: 'resolveAuditAccess' },
  'audits PUT /:id/responses/:questionId': { scoped: 'resolveAuditAccess' },
  'bookings DELETE /:id': { scoped: 'scopedPropertyId + assertPropertyAccess' },
  'bookings GET /': { scoped: 'scopedPropertyId + assertPropertyAccess' },
  'bookings GET /:id': { scoped: 'scopedPropertyId + assertPropertyAccess' },
  'bookings GET /availability': { scoped: 'scopedPropertyId + assertPropertyAccess' },
  'bookings POST /': { scoped: 'scopedPropertyId + assertPropertyAccess' },
  'bookings PUT /:id': { scoped: 'scopedPropertyId + assertPropertyAccess' },
  'communications DELETE /:id': { scoped: 'scopedPropertyId' },
  'communications GET /': { scoped: 'scopedPropertyId' },
  'communications GET /logs': { scoped: 'scopedPropertyId' },
  'communications POST /': { scoped: 'scopedPropertyId' },
  'communications POST /bulk-send': { scoped: 'scopedPropertyId' },
  'communications POST /preview': { scoped: 'scopedPropertyId' },
  'communications PUT /:id': { scoped: 'scopedPropertyId' },
  'complaints GET /': { scoped: 'scopedPropertyId' },
  'complaints GET /:id': { scoped: 'scopedPropertyId' },
  'complaints GET /:id/timeline': { scoped: 'scopedPropertyId' },
  'complaints GET /stats/overview': { scoped: 'scopedPropertyId' },
  'complaints POST /': { scoped: 'scopedPropertyId' },
  'complaints PUT /:id': { scoped: 'scopedPropertyId' },
  'dashboard GET /charts': { scoped: 'effectivePropertyFilter cascaded through every metric' },
  'dashboard GET /stats': { scoped: 'effectivePropertyFilter cascaded through every metric' },
  'employees DELETE /:id': { scoped: 'employeeScopeFilter / loadEmployeeInScope' },
  'employees GET /': { scoped: 'employeeScopeFilter / loadEmployeeInScope' },
  'employees GET /:id': { scoped: 'employeeScopeFilter / loadEmployeeInScope' },
  'employees GET /:id/attendance': { scoped: 'employeeScopeFilter / loadEmployeeInScope' },
  'employees GET /:id/exit': { scoped: 'employeeScopeFilter / loadEmployeeInScope' },
  'employees GET /:id/leave-balances': { scoped: 'employeeScopeFilter / loadEmployeeInScope' },
  'employees GET /:id/performance': { scoped: 'employeeScopeFilter / loadEmployeeInScope' },
  'employees GET /by-date': { scoped: 'employeeScopeFilter / loadEmployeeInScope' },
  'employees GET /candidates': { scoped: 'employeeScopeFilter / loadEmployeeInScope' },
  'employees GET /candidates/:id': { scoped: 'employeeScopeFilter / loadEmployeeInScope' },
  'employees GET /export-csv': { scoped: 'employeeScopeFilter / loadEmployeeInScope' },
  'employees GET /job-requisitions': { scoped: 'employeeScopeFilter / loadEmployeeInScope' },
  'employees GET /stats/overview': { scoped: 'employeeScopeFilter / loadEmployeeInScope' },
  'employees POST /': { scoped: 'employeeScopeFilter / loadEmployeeInScope' },
  'employees POST /:id/exit': { scoped: 'employeeScopeFilter / loadEmployeeInScope' },
  'employees POST /:id/performance': { scoped: 'employeeScopeFilter / loadEmployeeInScope' },
  'employees POST /bulk': { scoped: 'employeeScopeFilter / loadEmployeeInScope' },
  'employees POST /candidates': { scoped: 'employeeScopeFilter / loadEmployeeInScope' },
  'employees POST /candidates/:id/interviews': { scoped: 'employeeScopeFilter / loadEmployeeInScope' },
  'employees POST /candidates/:id/offers': { scoped: 'employeeScopeFilter / loadEmployeeInScope' },
  'employees POST /exits/:eid/finalize': { scoped: 'employeeScopeFilter / loadEmployeeInScope' },
  'employees POST /job-requisitions': { scoped: 'employeeScopeFilter / loadEmployeeInScope' },
  'employees PUT /:id': { scoped: 'employeeScopeFilter / loadEmployeeInScope' },
  'employees PUT /candidates/:id': { scoped: 'employeeScopeFilter / loadEmployeeInScope' },
  'employees PUT /exit-assets/:aid': { scoped: 'employeeScopeFilter / loadEmployeeInScope' },
  'employees PUT /exit-clearances/:cid': { scoped: 'employeeScopeFilter / loadEmployeeInScope' },
  'executive GET /complaints-resolution': { exempt: 'org-wide executive dashboard; EXECUTIVE_DASHBOARD is held only by org-wide roles' },
  'executive GET /headcount': { exempt: 'org-wide executive dashboard; EXECUTIVE_DASHBOARD is held only by org-wide roles' },
  'executive GET /kpis': { exempt: 'org-wide executive dashboard; EXECUTIVE_DASHBOARD is held only by org-wide roles' },
  'executive GET /lead-funnel': { exempt: 'org-wide executive dashboard; EXECUTIVE_DASHBOARD is held only by org-wide roles' },
  'executive GET /occupancy-by-property': { exempt: 'org-wide executive dashboard; EXECUTIVE_DASHBOARD is held only by org-wide roles' },
  'executive GET /portfolio-breakdown': { exempt: 'org-wide executive dashboard; EXECUTIVE_DASHBOARD is held only by org-wide roles' },
  'executive GET /revenue-trend': { exempt: 'org-wide executive dashboard; EXECUTIVE_DASHBOARD is held only by org-wide roles' },
  'executive GET /top-overdue': { exempt: 'org-wide executive dashboard; EXECUTIVE_DASHBOARD is held only by org-wide roles' },
  'executive GET /top-sla-breached': { exempt: 'org-wide executive dashboard; EXECUTIVE_DASHBOARD is held only by org-wide roles' },
  'finance DELETE /billing-cycles/:id': { scoped: 'effectivePropertyFilter / propertyScopeOrGlobal; writes pinned' },
  'finance DELETE /expense-categories/:id': { scoped: 'effectivePropertyFilter / propertyScopeOrGlobal; writes pinned' },
  'finance DELETE /expenses/:id': { scoped: 'effectivePropertyFilter / propertyScopeOrGlobal; writes pinned' },
  'finance DELETE /reminder-rules/:id': { scoped: 'effectivePropertyFilter / propertyScopeOrGlobal; writes pinned' },
  'finance GET /bank-imports': { scoped: 'effectivePropertyFilter / propertyScopeOrGlobal; writes pinned' },
  'finance GET /bank-imports/:id/lines': { scoped: 'effectivePropertyFilter / propertyScopeOrGlobal; writes pinned' },
  'finance GET /billing-cycles': { scoped: 'effectivePropertyFilter / propertyScopeOrGlobal; writes pinned' },
  'finance GET /billing-runs': { scoped: 'effectivePropertyFilter / propertyScopeOrGlobal; writes pinned' },
  'finance GET /expense-categories': { scoped: 'effectivePropertyFilter / propertyScopeOrGlobal; writes pinned' },
  'finance GET /expenses': { scoped: 'effectivePropertyFilter / propertyScopeOrGlobal; writes pinned' },
  'finance GET /expenses/:id/events': { scoped: 'effectivePropertyFilter / propertyScopeOrGlobal; writes pinned' },
  'finance GET /finance-summary': { scoped: 'effectivePropertyFilter / propertyScopeOrGlobal; writes pinned' },
  'finance GET /reminder-logs': { scoped: 'effectivePropertyFilter / propertyScopeOrGlobal; writes pinned' },
  'finance GET /reminder-rules': { scoped: 'effectivePropertyFilter / propertyScopeOrGlobal; writes pinned' },
  'finance GET /residents/:id/reminder-count': { scoped: 'effectivePropertyFilter / propertyScopeOrGlobal; writes pinned' },
  'finance POST /bank-imports': { scoped: 'effectivePropertyFilter / propertyScopeOrGlobal; writes pinned' },
  'finance POST /bank-lines/:id/confirm': { scoped: 'effectivePropertyFilter / propertyScopeOrGlobal; writes pinned' },
  'finance POST /bank-lines/:id/ignore': { scoped: 'effectivePropertyFilter / propertyScopeOrGlobal; writes pinned' },
  'finance POST /billing-cycles': { scoped: 'effectivePropertyFilter / propertyScopeOrGlobal; writes pinned' },
  'finance POST /billing-cycles/:id/run': { scoped: 'effectivePropertyFilter / propertyScopeOrGlobal; writes pinned' },
  'finance POST /expense-categories': { scoped: 'effectivePropertyFilter / propertyScopeOrGlobal; writes pinned' },
  'finance POST /expenses': { scoped: 'effectivePropertyFilter / propertyScopeOrGlobal; writes pinned' },
  'finance POST /expenses/:id/transition': { scoped: 'effectivePropertyFilter / propertyScopeOrGlobal; writes pinned' },
  'finance POST /reminder-rules': { scoped: 'effectivePropertyFilter / propertyScopeOrGlobal; writes pinned' },
  'finance POST /reminder-rules/:id/run': { scoped: 'effectivePropertyFilter / propertyScopeOrGlobal; writes pinned' },
  'finance POST /reminders/send': { scoped: 'effectivePropertyFilter / propertyScopeOrGlobal; writes pinned' },
  'finance PUT /billing-cycles/:id': { scoped: 'effectivePropertyFilter / propertyScopeOrGlobal; writes pinned' },
  'finance PUT /expenses/:id': { scoped: 'effectivePropertyFilter / propertyScopeOrGlobal; writes pinned' },
  'finance PUT /reminder-rules/:id': { scoped: 'effectivePropertyFilter / propertyScopeOrGlobal; writes pinned' },
  'food DELETE /agencies/:id': { scoped: 'resolveAccessiblePropertyIds' },
  'food DELETE /agency-locations/:id': { scoped: 'resolveAccessiblePropertyIds' },
  'food DELETE /agency-vehicles/:id': { scoped: 'resolveAccessiblePropertyIds' },
  'food DELETE /cities/:id': { scoped: 'resolveAccessiblePropertyIds' },
  'food DELETE /clusters/:id': { scoped: 'resolveAccessiblePropertyIds' },
  'food DELETE /composition-rules/:id': { scoped: 'resolveAccessiblePropertyIds' },
  'food DELETE /delivery-partners/:id': { scoped: 'resolveAccessiblePropertyIds' },
  'food DELETE /dishes/:id': { scoped: 'resolveAccessiblePropertyIds' },
  'food DELETE /ingredients/:id': { scoped: 'resolveAccessiblePropertyIds' },
  'food DELETE /menu-rotation/:id': { scoped: 'resolveAccessiblePropertyIds' },
  'food DELETE /order-draft': { scoped: 'resolveAccessiblePropertyIds' },
  'food DELETE /rules/:id': { scoped: 'resolveAccessiblePropertyIds' },
  'food DELETE /scopes/:id': { scoped: 'resolveAccessiblePropertyIds' },
  'food DELETE /zones/:id': { scoped: 'resolveAccessiblePropertyIds' },
  'food GET /agencies': { scoped: 'resolveAccessiblePropertyIds' },
  'food GET /agencies/:id/kitchens': { scoped: 'resolveAccessiblePropertyIds' },
  'food GET /cities': { scoped: 'resolveAccessiblePropertyIds' },
  'food GET /clusters': { scoped: 'resolveAccessiblePropertyIds' },
  'food GET /composition-rules': { scoped: 'resolveAccessiblePropertyIds' },
  'food GET /dashboard': { scoped: 'resolveAccessiblePropertyIds' },
  'food GET /delivery-partners': { scoped: 'resolveAccessiblePropertyIds' },
  'food GET /dishes': { scoped: 'resolveAccessiblePropertyIds' },
  'food GET /dishes/:id': { scoped: 'resolveAccessiblePropertyIds' },
  'food GET /food-users': { scoped: 'resolveAccessiblePropertyIds' },
  'food GET /ingredients': { scoped: 'resolveAccessiblePropertyIds' },
  'food GET /kitchen-summary': { scoped: 'resolveAccessiblePropertyIds' },
  'food GET /kitchens/:id/agencies': { scoped: 'resolveAccessiblePropertyIds' },
  'food GET /lookups': { scoped: 'resolveAccessiblePropertyIds' },
  'food GET /menu-rotation': { scoped: 'resolveAccessiblePropertyIds' },
  'food GET /menu-rotation/auto-fill': { scoped: 'resolveAccessiblePropertyIds' },
  'food GET /menu-rotation/export.csv': { scoped: 'resolveAccessiblePropertyIds' },
  'food GET /menu-rotation/export.pdf': { scoped: 'resolveAccessiblePropertyIds' },
  'food GET /menu-rotation/resolve': { scoped: 'resolveAccessiblePropertyIds' },
  'food GET /menu-rotation/validate': { scoped: 'resolveAccessiblePropertyIds' },
  'food GET /order-draft': { scoped: 'resolveAccessiblePropertyIds' },
  'food GET /orders': { scoped: 'resolveAccessiblePropertyIds' },
  'food GET /orders/:id': { scoped: 'resolveAccessiblePropertyIds' },
  'food GET /orders/:id/kitchen-items': { scoped: 'resolveAccessiblePropertyIds' },
  'food GET /orders/track': { scoped: 'resolveAccessiblePropertyIds' },
  'food GET /property-options': { scoped: 'resolveAccessiblePropertyIds' },
  'food GET /reports': { scoped: 'resolveAccessiblePropertyIds' },
  'food GET /rules': { scoped: 'resolveAccessiblePropertyIds' },
  'food GET /scopes': { scoped: 'resolveAccessiblePropertyIds' },
  'food GET /waste-pending': { scoped: 'resolveAccessiblePropertyIds' },
  'food GET /zones': { scoped: 'resolveAccessiblePropertyIds' },
  'food PATCH /orders/:id/kitchen-items': { scoped: 'resolveAccessiblePropertyIds' },
  'food POST /agencies': { scoped: 'resolveAccessiblePropertyIds' },
  'food POST /agencies/:id/locations': { scoped: 'resolveAccessiblePropertyIds' },
  'food POST /agencies/:id/vehicles': { scoped: 'resolveAccessiblePropertyIds' },
  'food POST /cities': { scoped: 'resolveAccessiblePropertyIds' },
  'food POST /clusters': { scoped: 'resolveAccessiblePropertyIds' },
  'food POST /composition-rules': { scoped: 'resolveAccessiblePropertyIds' },
  'food POST /delivery-partners': { scoped: 'resolveAccessiblePropertyIds' },
  'food POST /dishes': { scoped: 'resolveAccessiblePropertyIds' },
  'food POST /ingredients': { scoped: 'resolveAccessiblePropertyIds' },
  'food POST /menu-rotation': { scoped: 'resolveAccessiblePropertyIds' },
  'food POST /menu-rotation/bulk': { scoped: 'resolveAccessiblePropertyIds' },
  'food POST /orders': { scoped: 'resolveAccessiblePropertyIds' },
  'food POST /orders/:id/additional-food': { scoped: 'resolveAccessiblePropertyIds' },
  'food POST /orders/:id/cancel': { scoped: 'resolveAccessiblePropertyIds' },
  'food POST /orders/:id/confirm-delivery': { scoped: 'resolveAccessiblePropertyIds' },
  'food POST /orders/:id/dispatch': { scoped: 'resolveAccessiblePropertyIds' },
  'food POST /orders/:id/waste': { scoped: 'resolveAccessiblePropertyIds' },
  'food POST /orders/dispatch/bulk': { scoped: 'resolveAccessiblePropertyIds' },
  'food POST /properties/:id/assign-cluster': { scoped: 'resolveAccessiblePropertyIds' },
  'food POST /rules': { scoped: 'resolveAccessiblePropertyIds' },
  'food POST /scopes': { scoped: 'resolveAccessiblePropertyIds' },
  'food POST /zones': { scoped: 'resolveAccessiblePropertyIds' },
  'food PUT /agencies/:id': { scoped: 'resolveAccessiblePropertyIds' },
  'food PUT /agencies/:id/kitchens': { scoped: 'resolveAccessiblePropertyIds' },
  'food PUT /agency-locations/:id': { scoped: 'resolveAccessiblePropertyIds' },
  'food PUT /agency-vehicles/:id': { scoped: 'resolveAccessiblePropertyIds' },
  'food PUT /cities/:id': { scoped: 'resolveAccessiblePropertyIds' },
  'food PUT /clusters/:id': { scoped: 'resolveAccessiblePropertyIds' },
  'food PUT /composition-rules/:id': { scoped: 'resolveAccessiblePropertyIds' },
  'food PUT /delivery-partners/:id': { scoped: 'resolveAccessiblePropertyIds' },
  'food PUT /dishes/:id': { scoped: 'resolveAccessiblePropertyIds' },
  'food PUT /ingredients/:id': { scoped: 'resolveAccessiblePropertyIds' },
  'food PUT /menu-rotation/:id': { scoped: 'resolveAccessiblePropertyIds' },
  'food PUT /menu-rotation/slot': { scoped: 'resolveAccessiblePropertyIds' },
  'food PUT /order-draft': { scoped: 'resolveAccessiblePropertyIds' },
  'food PUT /orders/:id': { scoped: 'resolveAccessiblePropertyIds' },
  'food PUT /rules/:id': { scoped: 'resolveAccessiblePropertyIds' },
  'food PUT /zones/:id': { scoped: 'resolveAccessiblePropertyIds' },
  'food-ops DELETE /brands/:id': { scoped: 'resolveAccessiblePropertyIds' },
  'food-ops DELETE /cutoff-config/:id': { scoped: 'resolveAccessiblePropertyIds' },
  'food-ops DELETE /kitchens/:id': { scoped: 'resolveAccessiblePropertyIds' },
  'food-ops DELETE /meal-config/:mealType': { scoped: 'resolveAccessiblePropertyIds' },
  'food-ops DELETE /meal-windows/:id': { scoped: 'resolveAccessiblePropertyIds' },
  'food-ops GET /analytics': { scoped: 'resolveAccessiblePropertyIds' },
  'food-ops GET /brands': { scoped: 'resolveAccessiblePropertyIds' },
  'food-ops GET /cutoff-config': { scoped: 'resolveAccessiblePropertyIds' },
  'food-ops GET /cutoffs': { scoped: 'resolveAccessiblePropertyIds' },
  'food-ops GET /dispatches': { scoped: 'resolveAccessiblePropertyIds' },
  'food-ops GET /dispatches/:id': { scoped: 'resolveAccessiblePropertyIds' },
  'food-ops GET /dispatches/:id/events': { scoped: 'resolveAccessiblePropertyIds' },
  'food-ops GET /dispatches/active-vehicles': { scoped: 'resolveAccessiblePropertyIds' },
  'food-ops GET /guests': { scoped: 'resolveAccessiblePropertyIds' },
  'food-ops GET /hierarchy': { scoped: 'resolveAccessiblePropertyIds' },
  'food-ops GET /home-analytics': { scoped: 'resolveAccessiblePropertyIds' },
  'food-ops GET /kitchen-by-pincode': { scoped: 'resolveAccessiblePropertyIds' },
  'food-ops GET /kitchens': { scoped: 'resolveAccessiblePropertyIds' },
  'food-ops GET /meal-config': { scoped: 'resolveAccessiblePropertyIds' },
  'food-ops GET /meal-windows': { scoped: 'resolveAccessiblePropertyIds' },
  'food-ops GET /menu/full': { scoped: 'resolveAccessiblePropertyIds' },
  'food-ops GET /my-properties': { scoped: 'resolveAccessiblePropertyIds' },
  'food-ops GET /next-orders': { scoped: 'resolveAccessiblePropertyIds' },
  'food-ops GET /order-preview': { scoped: 'resolveAccessiblePropertyIds' },
  'food-ops GET /property-overview': { scoped: 'resolveAccessiblePropertyIds' },
  'food-ops GET /reports/on-time': { scoped: 'resolveAccessiblePropertyIds' },
  'food-ops GET /reports/variance': { scoped: 'resolveAccessiblePropertyIds' },
  'food-ops GET /reports/variance-by-day': { scoped: 'resolveAccessiblePropertyIds' },
  'food-ops GET /revenue': { scoped: 'resolveAccessiblePropertyIds' },
  'food-ops GET /settings/ontime-tolerance': { scoped: 'resolveAccessiblePropertyIds' },
  'food-ops GET /settings/order-headroom': { scoped: 'resolveAccessiblePropertyIds' },
  'food-ops GET /system-config/food-defaults': { scoped: 'resolveAccessiblePropertyIds' },
  'food-ops GET /system-config/menu-rules': { scoped: 'resolveAccessiblePropertyIds' },
  'food-ops GET /waste-analytics': { scoped: 'resolveAccessiblePropertyIds' },
  'food-ops PATCH /dispatches/:id/orders/:orderId': { scoped: 'resolveAccessiblePropertyIds' },
  'food-ops PATCH /dispatches/:id/status': { scoped: 'resolveAccessiblePropertyIds' },
  'food-ops POST /brands': { scoped: 'resolveAccessiblePropertyIds' },
  'food-ops POST /cutoff-config': { scoped: 'resolveAccessiblePropertyIds' },
  'food-ops POST /dispatches': { scoped: 'resolveAccessiblePropertyIds' },
  'food-ops POST /dispatches/:id/cancel': { scoped: 'resolveAccessiblePropertyIds' },
  'food-ops POST /kitchens': { scoped: 'resolveAccessiblePropertyIds' },
  'food-ops POST /meal-windows': { scoped: 'resolveAccessiblePropertyIds' },
  'food-ops POST /menu/share': { scoped: 'resolveAccessiblePropertyIds' },
  'food-ops POST /menu/shares/:id/revoke': { scoped: 'resolveAccessiblePropertyIds' },
  'food-ops POST /order-batches': { scoped: 'resolveAccessiblePropertyIds' },
  'food-ops POST /orders/:id/accept': { scoped: 'resolveAccessiblePropertyIds' },
  'food-ops POST /orders/:id/reject': { scoped: 'resolveAccessiblePropertyIds' },
  'food-ops POST /properties/:id/assign-brand': { scoped: 'resolveAccessiblePropertyIds' },
  'food-ops POST /properties/:id/assign-kitchen': { scoped: 'resolveAccessiblePropertyIds' },
  'food-ops PUT /brands/:id': { scoped: 'resolveAccessiblePropertyIds' },
  'food-ops PUT /cutoff-config/:id': { scoped: 'resolveAccessiblePropertyIds' },
  'food-ops PUT /kitchens/:id': { scoped: 'resolveAccessiblePropertyIds' },
  'food-ops PUT /meal-config/:mealType': { scoped: 'resolveAccessiblePropertyIds' },
  'food-ops PUT /meal-windows/:id': { scoped: 'resolveAccessiblePropertyIds' },
  'food-ops PUT /system-config/menu-rules': { scoped: 'resolveAccessiblePropertyIds' },
  'kyc-esign GET /esign/:id': { scoped: 'residentInScope / recordResidentInScope (scopes via the resident)' },
  'kyc-esign GET /esign/:id/pdf': { scoped: 'residentInScope / recordResidentInScope (scopes via the resident)' },
  'kyc-esign GET /kyc/:id': { scoped: 'residentInScope / recordResidentInScope (scopes via the resident)' },
  'kyc-esign GET /kyc/:id/digilocker/initiate': { scoped: 'residentInScope / recordResidentInScope (scopes via the resident)' },
  'kyc-esign GET /kyc/:id/events': { scoped: 'residentInScope / recordResidentInScope (scopes via the resident)' },
  'kyc-esign GET /residents/:id/esign': { scoped: 'residentInScope / recordResidentInScope (scopes via the resident)' },
  'kyc-esign GET /residents/:id/kyc': { scoped: 'residentInScope / recordResidentInScope (scopes via the resident)' },
  'kyc-esign POST /esign/:id/void': { scoped: 'residentInScope / recordResidentInScope (scopes via the resident)' },
  'kyc-esign POST /kyc/:id/verify': { scoped: 'residentInScope / recordResidentInScope (scopes via the resident)' },
  'kyc-esign POST /residents/:id/agreement': { scoped: 'residentInScope / recordResidentInScope (scopes via the resident)' },
  'kyc-esign POST /residents/:id/esign': { scoped: 'residentInScope / recordResidentInScope (scopes via the resident)' },
  'kyc-esign POST /residents/:id/kyc': { scoped: 'residentInScope / recordResidentInScope (scopes via the resident)' },
  'laundry DELETE /:id': { scoped: 'scopedPropertyId + assertPropertyAccess' },
  'laundry GET /': { scoped: 'scopedPropertyId + assertPropertyAccess' },
  'laundry GET /:id': { scoped: 'scopedPropertyId + assertPropertyAccess' },
  'laundry POST /': { scoped: 'scopedPropertyId + assertPropertyAccess' },
  'laundry PUT /:id': { scoped: 'scopedPropertyId + assertPropertyAccess' },
  'lnd DELETE /:id': { exempt: 'org-wide learning catalogue — no property dimension' },
  'lnd GET /': { exempt: 'org-wide learning catalogue — no property dimension' },
  'lnd GET /:id': { exempt: 'org-wide learning catalogue — no property dimension' },
  'lnd GET /:id/enrollments': { exempt: 'org-wide learning catalogue — no property dimension' },
  'lnd GET /stats': { exempt: 'org-wide learning catalogue — no property dimension' },
  'lnd POST /': { exempt: 'org-wide learning catalogue — no property dimension' },
  'lnd POST /:id/enroll': { exempt: 'org-wide learning catalogue — no property dimension' },
  'lnd POST /:id/progress': { exempt: 'org-wide learning catalogue — no property dimension' },
  'lnd POST /:id/quiz': { exempt: 'org-wide learning catalogue — no property dimension' },
  'lnd POST /:id/remind': { exempt: 'org-wide learning catalogue — no property dimension' },
  'lnd PUT /:id': { exempt: 'org-wide learning catalogue — no property dimension' },
  'masters DELETE /:type/:id': { exempt: 'global master data (zones/cities/clusters/kitchens/brands) — not property-owned' },
  'masters GET /': { exempt: 'global master data (zones/cities/clusters/kitchens/brands) — not property-owned' },
  'masters GET /:type': { exempt: 'global master data (zones/cities/clusters/kitchens/brands) — not property-owned' },
  'masters GET /:type/export.:fmt': { exempt: 'global master data (zones/cities/clusters/kitchens/brands) — not property-owned' },
  'masters PATCH /:type/:id': { exempt: 'global master data (zones/cities/clusters/kitchens/brands) — not property-owned' },
  'masters POST /:type': { exempt: 'global master data (zones/cities/clusters/kitchens/brands) — not property-owned' },
  'masters POST /:type/bulk': { exempt: 'global master data (zones/cities/clusters/kitchens/brands) — not property-owned' },
  'operations DELETE /assets/:id': { scoped: 'effectivePropertyFilter' },
  'operations DELETE /devices/:id': { scoped: 'effectivePropertyFilter' },
  'operations DELETE /meters/:id': { scoped: 'effectivePropertyFilter' },
  'operations DELETE /schedules/:id': { scoped: 'effectivePropertyFilter' },
  'operations GET /': { scoped: 'effectivePropertyFilter' },
  'operations GET /assets': { scoped: 'effectivePropertyFilter' },
  'operations GET /devices': { scoped: 'effectivePropertyFilter' },
  'operations GET /history/:residentId': { scoped: 'effectivePropertyFilter' },
  'operations GET /latest': { scoped: 'effectivePropertyFilter' },
  'operations GET /logs': { scoped: 'effectivePropertyFilter' },
  'operations GET /meters': { scoped: 'effectivePropertyFilter' },
  'operations GET /readings': { scoped: 'effectivePropertyFilter' },
  'operations GET /schedules': { scoped: 'effectivePropertyFilter' },
  'operations GET /summary': { scoped: 'effectivePropertyFilter' },
  'operations GET /tariffs': { scoped: 'effectivePropertyFilter' },
  'operations POST /': { scoped: 'effectivePropertyFilter' },
  'operations POST /:id/return': { scoped: 'effectivePropertyFilter' },
  'operations POST /assets': { scoped: 'effectivePropertyFilter' },
  'operations POST /devices': { scoped: 'effectivePropertyFilter' },
  'operations POST /devices/:id/rotate-token': { scoped: 'effectivePropertyFilter' },
  'operations POST /logs': { scoped: 'effectivePropertyFilter' },
  'operations POST /mark': { scoped: 'effectivePropertyFilter' },
  'operations POST /meters': { scoped: 'effectivePropertyFilter' },
  'operations POST /readings': { scoped: 'effectivePropertyFilter' },
  'operations POST /readings/:id/post': { scoped: 'effectivePropertyFilter' },
  'operations POST /readings/bulk': { scoped: 'effectivePropertyFilter' },
  'operations POST /schedules': { scoped: 'effectivePropertyFilter' },
  'operations POST /tariffs': { scoped: 'effectivePropertyFilter' },
  'operations PUT /:id': { scoped: 'effectivePropertyFilter' },
  'operations PUT /assets/:id': { scoped: 'effectivePropertyFilter' },
  'operations PUT /devices/:id': { scoped: 'effectivePropertyFilter' },
  'operations PUT /meters/:id': { scoped: 'effectivePropertyFilter' },
  'operations PUT /schedules/:id': { scoped: 'effectivePropertyFilter' },
  'operations PUT /tariffs/:id': { scoped: 'effectivePropertyFilter' },
  'procurement DELETE /documents/:docId': { scoped: 'effectivePropertyFilter; assertWritableBody on writes' },
  'procurement DELETE /rate-contracts/:rcId': { scoped: 'effectivePropertyFilter; assertWritableBody on writes' },
  'procurement GET /': { scoped: 'effectivePropertyFilter; assertWritableBody on writes' },
  'procurement GET /:id': { scoped: 'effectivePropertyFilter; assertWritableBody on writes' },
  'procurement GET /:id/documents': { scoped: 'effectivePropertyFilter; assertWritableBody on writes' },
  'procurement GET /:id/movements': { scoped: 'effectivePropertyFilter; assertWritableBody on writes' },
  'procurement GET /:id/performance': { scoped: 'effectivePropertyFilter; assertWritableBody on writes' },
  'procurement GET /:id/purchase-orders': { scoped: 'effectivePropertyFilter; assertWritableBody on writes' },
  'procurement GET /:id/rate-contracts': { scoped: 'effectivePropertyFilter; assertWritableBody on writes' },
  'procurement GET /alerts': { scoped: 'effectivePropertyFilter; assertWritableBody on writes' },
  'procurement GET /item-suggestions': { scoped: 'effectivePropertyFilter; assertWritableBody on writes' },
  'procurement GET /stats': { scoped: 'effectivePropertyFilter; assertWritableBody on writes' },
  'procurement POST /': { scoped: 'effectivePropertyFilter; assertWritableBody on writes' },
  'procurement POST /:id/approve': { scoped: 'effectivePropertyFilter; assertWritableBody on writes' },
  'procurement POST /:id/audit': { scoped: 'effectivePropertyFilter; assertWritableBody on writes' },
  'procurement POST /:id/consume': { scoped: 'effectivePropertyFilter; assertWritableBody on writes' },
  'procurement POST /:id/documents': { scoped: 'effectivePropertyFilter; assertWritableBody on writes' },
  'procurement POST /:id/rate-contracts': { scoped: 'effectivePropertyFilter; assertWritableBody on writes' },
  'procurement POST /:id/reject': { scoped: 'effectivePropertyFilter; assertWritableBody on writes' },
  'procurement POST /:id/send': { scoped: 'effectivePropertyFilter; assertWritableBody on writes' },
  'procurement PUT /:id': { scoped: 'effectivePropertyFilter; assertWritableBody on writes' },
  'procurement PUT /rate-contracts/:rcId': { scoped: 'effectivePropertyFilter; assertWritableBody on writes' },
  'properties DELETE /:id': { scoped: 'assertPropertyAccess' },
  'properties DELETE /:id/photos/:photoId': { scoped: 'assertPropertyAccess' },
  'properties GET /': { scoped: 'assertPropertyAccess' },
  'properties GET /:id': { scoped: 'assertPropertyAccess' },
  'properties GET /:id/photos': { scoped: 'assertPropertyAccess' },
  'properties GET /assignable-unit-leads': { scoped: 'assertPropertyAccess' },
  'properties PATCH /:id/photos/:photoId': { scoped: 'assertPropertyAccess' },
  'properties POST /': { scoped: 'assertPropertyAccess' },
  'properties POST /:id/photos': { scoped: 'assertPropertyAccess' },
  'properties PUT /:id': { scoped: 'assertPropertyAccess' },
  'residents DELETE /:id': { scoped: 'scopedPropertyId + assertPropertyAccess' },
  'residents GET /': { scoped: 'scopedPropertyId + assertPropertyAccess' },
  'residents GET /:id': { scoped: 'scopedPropertyId + assertPropertyAccess' },
  'residents GET /:id/ledger': { scoped: 'scopedPropertyId + assertPropertyAccess' },
  'residents GET /:id/payments': { scoped: 'scopedPropertyId + assertPropertyAccess' },
  'residents POST /': { scoped: 'scopedPropertyId + assertPropertyAccess' },
  'residents POST /:id/checkout': { scoped: 'scopedPropertyId + assertPropertyAccess' },
  'residents POST /:id/ledger': { scoped: 'scopedPropertyId + assertPropertyAccess' },
  'residents POST /:id/payment-link': { scoped: 'scopedPropertyId + assertPropertyAccess' },
  'residents POST /:id/payments': { scoped: 'scopedPropertyId + assertPropertyAccess' },
  'residents POST /bulk-rent': { scoped: 'scopedPropertyId + assertPropertyAccess' },
  'residents PUT /:id': { scoped: 'scopedPropertyId + assertPropertyAccess' },
  'rooms DELETE /:id': { scoped: 'effectivePropertyFilter / loadRoomInScope' },
  'rooms GET /': { scoped: 'effectivePropertyFilter / loadRoomInScope' },
  'rooms GET /:id': { scoped: 'effectivePropertyFilter / loadRoomInScope' },
  'rooms POST /': { scoped: 'effectivePropertyFilter / loadRoomInScope' },
  'rooms PUT /:id': { scoped: 'effectivePropertyFilter / loadRoomInScope' },
  'sales DELETE /:id': { scoped: 'effectivePropertyFilter; create+convert pinned' },
  'sales GET /': { scoped: 'effectivePropertyFilter; create+convert pinned' },
  'sales GET /:id': { scoped: 'effectivePropertyFilter; create+convert pinned' },
  'sales GET /:id/activities': { scoped: 'effectivePropertyFilter; create+convert pinned' },
  'sales GET /export-csv': { scoped: 'effectivePropertyFilter; create+convert pinned' },
  'sales GET /stats': { scoped: 'effectivePropertyFilter; create+convert pinned' },
  'sales POST /': { scoped: 'effectivePropertyFilter; create+convert pinned' },
  'sales POST /:id/activities': { scoped: 'effectivePropertyFilter; create+convert pinned' },
  'sales POST /:id/convert': { scoped: 'effectivePropertyFilter; create+convert pinned' },
  'sales POST /:id/follow-up': { scoped: 'effectivePropertyFilter; create+convert pinned' },
  'sales POST /:id/mark-lost': { scoped: 'effectivePropertyFilter; create+convert pinned' },
  'sales POST /:id/schedule-visit': { scoped: 'effectivePropertyFilter; create+convert pinned' },
  'sales POST /:id/visit-outcome': { scoped: 'effectivePropertyFilter; create+convert pinned' },
  'sales PUT /:id': { scoped: 'effectivePropertyFilter; create+convert pinned' },
  'settings DELETE /routing/:id': { exempt: 'global system configuration' },
  'settings GET /audit-log': { exempt: 'global system configuration' },
  'settings GET /audit-log/facets': { exempt: 'global system configuration' },
  'settings GET /integrations': { exempt: 'global system configuration' },
  'settings GET /kyc-gate': { exempt: 'global system configuration' },
  'settings GET /routing': { exempt: 'global system configuration' },
  'settings GET /sla': { exempt: 'global system configuration' },
  'settings POST /routing': { exempt: 'global system configuration' },
  'settings PUT /kyc-gate': { exempt: 'global system configuration' },
  'settings PUT /sla/:category': { exempt: 'global system configuration' },
  'users DELETE /:id': { scoped: 'scopedPropertyId on list/create/edit' },
  'users GET /': { scoped: 'scopedPropertyId on list/create/edit' },
  'users POST /': { scoped: 'scopedPropertyId on list/create/edit' },
  'users PUT /:id': { scoped: 'scopedPropertyId on list/create/edit' },
  'wallet GET /wallet/config/:propertyId': { scoped: 'assertPropertyAccess' },
  'wallet GET /wallet/overview': { scoped: 'assertPropertyAccess' },
  'wallet GET /wallet/residents/:residentId': { scoped: 'assertPropertyAccess' },
  'wallet GET /wallet/residents/:residentId/transactions': { scoped: 'assertPropertyAccess' },
  'wallet PATCH /wallet/residents/:residentId/toggle': { scoped: 'assertPropertyAccess' },
  'wallet POST /wallet/:residentId/topup-link': { scoped: 'assertPropertyAccess' },
  'wallet POST /wallet/residents/:residentId/adjust': { scoped: 'assertPropertyAccess' },
  'wallet POST /wallet/residents/:residentId/checkout-refund': { scoped: 'assertPropertyAccess' },
  'wallet POST /wallet/residents/:residentId/partial-pay': { scoped: 'assertPropertyAccess' },
  'wallet POST /wallet/residents/:residentId/pay': { scoped: 'assertPropertyAccess' },
  'wallet POST /wallet/residents/:residentId/reversal': { scoped: 'assertPropertyAccess' },
  'wallet POST /wallet/residents/:residentId/topup': { scoped: 'assertPropertyAccess' },
  'wallet PUT /wallet/config/:propertyId': { scoped: 'assertPropertyAccess' },
};
