-- 2026-09-29_role_taxonomy.sql
--
-- RUN THIS BEFORE `drizzle-kit push` ON ANY ENVIRONMENT THAT PREDATES IT.
--
-- Replaces the role set with the 24 the business names, plus one break-glass
-- role that is deliberately not on that list.
--
-- ── What this does to people ────────────────────────────────────────────────
-- Nobody loses access. Two roles retire into survivors:
--
--   WARDEN         -> UNIT_LEAD   (1 holder)
--   FNB_ZONAL_HEAD -> FNB_MANAGER (1 holder)
--
-- UNIT_LEAD was a FOOD role — FOOD_* and AUDIT_* only, no Properties, Residents
-- or Complaints — while WARDEN was the property-operations role. They were
-- different jobs that happened to share a scope. With one property-level role
-- in the new taxonomy it has to carry both, so UNIT_LEAD's matrix is now the
-- union of the two. C3 is unaffected: WARDEN held no FOOD_* cells, so dispatch
-- and confirm-receipt still cannot meet in one role.
--
-- ── What is NOT removed, and why ────────────────────────────────────────────
--   OPS_EXCELLENCE  break-glass. Holds everything by rule and cannot be edited,
--                   which is what makes it the lockout backstop that
--                   assertAccessControlReachable counts. Never offered in a
--                   picker, so it does not appear in the business list.
--   UNASSIGNED      the default users.role before any role is assigned.
--                   Deleting it breaks user creation. It is the ABSENCE of a
--                   role, not a role.
--
-- The six AUDIT.* personas DO go: audit is a module with its own
-- functionalities, and the common roles are granted those. It is not a
-- module with a private role system.
--
-- Idempotent: re-running changes nothing.

BEGIN;

-- 1. New role keys must exist in the users.role enum before anything writes one.
ALTER TYPE user_role ADD VALUE IF NOT EXISTS 'RM_MANAGER';
ALTER TYPE user_role ADD VALUE IF NOT EXISTS 'RM_SUPERVISOR';
ALTER TYPE user_role ADD VALUE IF NOT EXISTS 'HOUSEKEEPING_MANAGER';
ALTER TYPE user_role ADD VALUE IF NOT EXISTS 'HOUSEKEEPING_SUPERVISOR';
ALTER TYPE user_role ADD VALUE IF NOT EXISTS 'CARE_DESK_AGENT';
ALTER TYPE user_role ADD VALUE IF NOT EXISTS 'FINANCE_EXECUTIVE';
ALTER TYPE user_role ADD VALUE IF NOT EXISTS 'SALES_ADMIN';
ALTER TYPE user_role ADD VALUE IF NOT EXISTS 'SALES_MANAGER';

-- Postgres cannot remove an enum value, so the retired ones stay in the type.
-- They are unreachable once nothing references them, which steps 2-4 ensure.

COMMIT;
BEGIN;

-- 2. Move the holders of retired roles onto their survivor.
UPDATE users            SET role     = 'UNIT_LEAD' WHERE role::text = 'WARDEN';
UPDATE user_roles       SET role_key = 'UNIT_LEAD' WHERE role_key    = 'WARDEN';
UPDATE access_grants    SET role_key = 'UNIT_LEAD' WHERE role_key    = 'WARDEN';
UPDATE privileges       SET role_key = 'UNIT_LEAD' WHERE role_key    = 'WARDEN';
UPDATE users            SET role     = 'FNB_MANAGER' WHERE role::text = 'FNB_ZONAL_HEAD';
UPDATE user_roles       SET role_key = 'FNB_MANAGER' WHERE role_key    = 'FNB_ZONAL_HEAD';
UPDATE access_grants    SET role_key = 'FNB_MANAGER' WHERE role_key    = 'FNB_ZONAL_HEAD';
UPDATE privileges       SET role_key = 'FNB_MANAGER' WHERE role_key    = 'FNB_ZONAL_HEAD';

-- 3. Retire what is left. Memberships first, then the cells, then the role.
--    A retired role with no memberships costs nobody anything.
DELETE FROM user_roles           WHERE role_key IN ('WARDEN', 'FNB_ZONAL_HEAD', 'PROJECTS_MANAGER', 'PROPERTY_ACQUISITION', 'VENDOR_RESTRICTED', 'NIGHT_WRDEN', 'RESIDENT', 'AUDIT.ADMIN', 'AUDIT.AUDITOR', 'AUDIT.AUDITEE', 'AUDIT.REVIEWER', 'AUDIT.SCHEDULER', 'AUDIT.VIEWER');
DELETE FROM access_grants        WHERE role_key IN ('WARDEN', 'FNB_ZONAL_HEAD', 'PROJECTS_MANAGER', 'PROPERTY_ACQUISITION', 'VENDOR_RESTRICTED', 'NIGHT_WRDEN', 'RESIDENT', 'AUDIT.ADMIN', 'AUDIT.AUDITOR', 'AUDIT.AUDITEE', 'AUDIT.REVIEWER', 'AUDIT.SCHEDULER', 'AUDIT.VIEWER');
DELETE FROM privileges           WHERE role_key IN ('WARDEN', 'FNB_ZONAL_HEAD', 'PROJECTS_MANAGER', 'PROPERTY_ACQUISITION', 'VENDOR_RESTRICTED', 'NIGHT_WRDEN', 'RESIDENT', 'AUDIT.ADMIN', 'AUDIT.AUDITOR', 'AUDIT.AUDITEE', 'AUDIT.REVIEWER', 'AUDIT.SCHEDULER', 'AUDIT.VIEWER');
DELETE FROM role_functionalities WHERE role_key IN ('WARDEN', 'FNB_ZONAL_HEAD', 'PROJECTS_MANAGER', 'PROPERTY_ACQUISITION', 'VENDOR_RESTRICTED', 'NIGHT_WRDEN', 'RESIDENT', 'AUDIT.ADMIN', 'AUDIT.AUDITOR', 'AUDIT.AUDITEE', 'AUDIT.REVIEWER', 'AUDIT.SCHEDULER', 'AUDIT.VIEWER');
DELETE FROM roles                WHERE key      IN ('WARDEN', 'FNB_ZONAL_HEAD', 'PROJECTS_MANAGER', 'PROPERTY_ACQUISITION', 'VENDOR_RESTRICTED', 'NIGHT_WRDEN', 'RESIDENT', 'AUDIT.ADMIN', 'AUDIT.AUDITOR', 'AUDIT.AUDITEE', 'AUDIT.REVIEWER', 'AUDIT.SCHEDULER', 'AUDIT.VIEWER');

-- 4. The surviving and new roles, with the labels the business uses.
INSERT INTO roles (key, label, rank, is_system, anchor_level) VALUES
  ('SUPER_ADMIN', 'Super Admin', 100, true, NULL),
  ('OPS_EXCELLENCE', 'Ops Excellence (break-glass)', 100, true, NULL),
  ('AUDIT_READONLY', 'Viewer', 80, true, NULL),
  ('OPERATIONS_MANAGER', 'Admin (Ops Excellence)', 80, false, NULL),
  ('SENIOR_VICE_PRESIDENT', 'Leadership – View All', 80, false, NULL),
  ('ZONAL_HEAD', 'Zonal Head', 80, false, 'ZONE'),
  ('CITY_HEAD', 'City Head', 50, false, 'CITY'),
  ('CLUSTER_MANAGER', 'Cluster Manager', 50, false, 'CLUSTER'),
  ('UNIT_LEAD', 'Unit Lead', 20, false, 'PROPERTY'),
  ('RM_MANAGER', 'R&M Manager', 80, false, NULL),
  ('RM_SUPERVISOR', 'R&M Supervisor', 20, false, 'PROPERTY'),
  ('HOUSEKEEPING_MANAGER', 'Housekeeping Manager', 80, false, NULL),
  ('HOUSEKEEPING_SUPERVISOR', 'Housekeeping Supervisor', 20, false, 'PROPERTY'),
  ('CUSTOMER_EXPERIENCE', 'CX Admin (Care Desk)', 80, false, NULL),
  ('CARE_DESK_AGENT', 'Care Desk Agent', 50, false, NULL),
  ('FNB_MANAGER', 'F&B Admin', 50, false, NULL),
  ('FNB_SUPERVISOR', 'F&B Supervisor', 50, false, NULL),
  ('KITCHEN_MANAGER', 'F&B Store', 20, false, 'KITCHEN'),
  ('FINANCE', 'Finance Admin', 80, false, NULL),
  ('FINANCE_EXECUTIVE', 'Finance Executive', 50, false, NULL),
  ('PROCUREMENT_MANAGER', 'Procurement', 80, false, NULL),
  ('SALES_ADMIN', 'Sales Admin', 80, false, NULL),
  ('SALES_MANAGER', 'Sales Manager', 50, false, 'CLUSTER'),
  ('SALES_EXECUTIVE', 'Sales Executive', 20, false, 'PROPERTY'),
  ('HR_MANAGER', 'HR Admin', 80, false, NULL)
ON CONFLICT (key) DO UPDATE
  SET label = EXCLUDED.label, rank = EXCLUDED.rank,
      is_system = EXCLUDED.is_system, anchor_level = EXCLUDED.anchor_level;

-- 5. The permission cells, straight from the code matrix. Replaced wholesale
--    per role: the matrix IS the role, and a partial apply would leave a role
--    holding a mixture nobody chose.
DELETE FROM role_functionalities WHERE role_key IN ('CARE_DESK_AGENT', 'CITY_HEAD', 'CLUSTER_MANAGER', 'CUSTOMER_EXPERIENCE', 'FINANCE', 'FINANCE_EXECUTIVE', 'FNB_MANAGER', 'FNB_SUPERVISOR', 'HOUSEKEEPING_MANAGER', 'HOUSEKEEPING_SUPERVISOR', 'HR_MANAGER', 'KITCHEN_MANAGER', 'OPERATIONS_MANAGER', 'PROCUREMENT_MANAGER', 'RM_MANAGER', 'RM_SUPERVISOR', 'SALES_ADMIN', 'SALES_EXECUTIVE', 'SALES_MANAGER', 'SENIOR_VICE_PRESIDENT', 'UNIT_LEAD', 'ZONAL_HEAD');
INSERT INTO role_functionalities (id, role_key, functionality, action, allowed) VALUES
  (gen_random_uuid()::text, 'OPERATIONS_MANAGER', 'DASHBOARD', 'view_dashboard', true),
  (gen_random_uuid()::text, 'OPERATIONS_MANAGER', 'PROPERTIES', 'view_property', true),
  (gen_random_uuid()::text, 'OPERATIONS_MANAGER', 'PROPERTIES', 'add_property', true),
  (gen_random_uuid()::text, 'OPERATIONS_MANAGER', 'PROPERTIES', 'edit_property', true),
  (gen_random_uuid()::text, 'OPERATIONS_MANAGER', 'PROPERTIES', 'delete_property', true),
  (gen_random_uuid()::text, 'OPERATIONS_MANAGER', 'RESIDENTS', 'view_resident', true),
  (gen_random_uuid()::text, 'OPERATIONS_MANAGER', 'RESIDENTS', 'add_resident', true),
  (gen_random_uuid()::text, 'OPERATIONS_MANAGER', 'RESIDENTS', 'edit_resident', true),
  (gen_random_uuid()::text, 'OPERATIONS_MANAGER', 'RESIDENTS', 'delete_resident', true),
  (gen_random_uuid()::text, 'OPERATIONS_MANAGER', 'RESIDENTS', 'export_resident', true),
  (gen_random_uuid()::text, 'OPERATIONS_MANAGER', 'COMPLAINT_TICKETS', 'view_complaint', true),
  (gen_random_uuid()::text, 'OPERATIONS_MANAGER', 'COMPLAINT_TICKETS', 'add_complaint', true),
  (gen_random_uuid()::text, 'OPERATIONS_MANAGER', 'COMPLAINT_TICKETS', 'edit_complaint', true),
  (gen_random_uuid()::text, 'OPERATIONS_MANAGER', 'COMPLAINT_TICKETS', 'delete_complaint', true),
  (gen_random_uuid()::text, 'OPERATIONS_MANAGER', 'COMPLAINT_TICKETS', 'assign_complaint', true),
  (gen_random_uuid()::text, 'OPERATIONS_MANAGER', 'COMPLAINT_TICKETS', 'close_complaint', true),
  (gen_random_uuid()::text, 'OPERATIONS_MANAGER', 'COMPLAINT_TICKETS', 'verify_complaint', true),
  (gen_random_uuid()::text, 'OPERATIONS_MANAGER', 'LAUNDRY_BATCHES', 'view_laundry_batche', true),
  (gen_random_uuid()::text, 'OPERATIONS_MANAGER', 'LAUNDRY_BATCHES', 'add_laundry_batche', true),
  (gen_random_uuid()::text, 'OPERATIONS_MANAGER', 'LAUNDRY_BATCHES', 'edit_laundry_batche', true),
  (gen_random_uuid()::text, 'OPERATIONS_MANAGER', 'LAUNDRY_BATCHES', 'delete_laundry_batche', true),
  (gen_random_uuid()::text, 'OPERATIONS_MANAGER', 'COMMUNICATIONS', 'view_communication', true),
  (gen_random_uuid()::text, 'OPERATIONS_MANAGER', 'COMMUNICATIONS', 'add_communication', true),
  (gen_random_uuid()::text, 'OPERATIONS_MANAGER', 'COMMUNICATIONS', 'edit_communication', true),
  (gen_random_uuid()::text, 'OPERATIONS_MANAGER', 'COMMUNICATIONS', 'delete_communication', true),
  (gen_random_uuid()::text, 'OPERATIONS_MANAGER', 'FACILITY', 'view_facility', true),
  (gen_random_uuid()::text, 'OPERATIONS_MANAGER', 'FACILITY', 'add_facility', true),
  (gen_random_uuid()::text, 'OPERATIONS_MANAGER', 'FACILITY', 'edit_facility', true),
  (gen_random_uuid()::text, 'OPERATIONS_MANAGER', 'FACILITY', 'delete_facility', true),
  (gen_random_uuid()::text, 'OPERATIONS_MANAGER', 'ELECTRICITY', 'view_electricity', true),
  (gen_random_uuid()::text, 'OPERATIONS_MANAGER', 'ELECTRICITY', 'add_electricity', true),
  (gen_random_uuid()::text, 'OPERATIONS_MANAGER', 'ELECTRICITY', 'edit_electricity', true),
  (gen_random_uuid()::text, 'OPERATIONS_MANAGER', 'ELECTRICITY', 'delete_electricity', true),
  (gen_random_uuid()::text, 'OPERATIONS_MANAGER', 'RESIDENT_ATTENDANCE', 'view_resident_attendance', true),
  (gen_random_uuid()::text, 'OPERATIONS_MANAGER', 'RESIDENT_ATTENDANCE', 'add_resident_attendance', true),
  (gen_random_uuid()::text, 'OPERATIONS_MANAGER', 'RESIDENT_ATTENDANCE', 'edit_resident_attendance', true),
  (gen_random_uuid()::text, 'OPERATIONS_MANAGER', 'RESIDENT_ATTENDANCE', 'delete_resident_attendance', true),
  (gen_random_uuid()::text, 'OPERATIONS_MANAGER', 'IOT', 'view_iot', true),
  (gen_random_uuid()::text, 'OPERATIONS_MANAGER', 'IOT', 'add_iot', true),
  (gen_random_uuid()::text, 'OPERATIONS_MANAGER', 'IOT', 'edit_iot', true),
  (gen_random_uuid()::text, 'OPERATIONS_MANAGER', 'IOT', 'delete_iot', true),
  (gen_random_uuid()::text, 'OPERATIONS_MANAGER', 'WALLET', 'view_wallet', true),
  (gen_random_uuid()::text, 'SENIOR_VICE_PRESIDENT', 'DASHBOARD', 'view_dashboard', true),
  (gen_random_uuid()::text, 'SENIOR_VICE_PRESIDENT', 'EXECUTIVE_DASHBOARD', 'view_executive_dashboard', true),
  (gen_random_uuid()::text, 'SENIOR_VICE_PRESIDENT', 'PROPERTIES', 'view_property', true),
  (gen_random_uuid()::text, 'SENIOR_VICE_PRESIDENT', 'RESIDENTS', 'view_resident', true),
  (gen_random_uuid()::text, 'SENIOR_VICE_PRESIDENT', 'RESIDENT_ATTENDANCE', 'view_resident_attendance', true),
  (gen_random_uuid()::text, 'SENIOR_VICE_PRESIDENT', 'COMMUNICATIONS', 'view_communication', true),
  (gen_random_uuid()::text, 'SENIOR_VICE_PRESIDENT', 'FACILITY', 'view_facility', true),
  (gen_random_uuid()::text, 'SENIOR_VICE_PRESIDENT', 'ELECTRICITY', 'view_electricity', true),
  (gen_random_uuid()::text, 'SENIOR_VICE_PRESIDENT', 'IOT', 'view_iot', true),
  (gen_random_uuid()::text, 'SENIOR_VICE_PRESIDENT', 'COMPLAINT_TICKETS', 'view_complaint', true),
  (gen_random_uuid()::text, 'SENIOR_VICE_PRESIDENT', 'COMPLAINT_ROUTING', 'view_routing_sla', true),
  (gen_random_uuid()::text, 'SENIOR_VICE_PRESIDENT', 'HOUSEKEEPING_TASKS', 'view_housekeeping_task', true),
  (gen_random_uuid()::text, 'SENIOR_VICE_PRESIDENT', 'LAUNDRY_BATCHES', 'view_laundry_batche', true),
  (gen_random_uuid()::text, 'SENIOR_VICE_PRESIDENT', 'FOOD_DASHBOARD', 'view_food_dashboard', true),
  (gen_random_uuid()::text, 'SENIOR_VICE_PRESIDENT', 'FOOD_ALL_ORDERS', 'view_order', true),
  (gen_random_uuid()::text, 'SENIOR_VICE_PRESIDENT', 'FOOD_PLACE_ORDER', 'view_order_form', true),
  (gen_random_uuid()::text, 'SENIOR_VICE_PRESIDENT', 'FOOD_RECEIVE_UPDATE', 'view_receive_update', true),
  (gen_random_uuid()::text, 'SENIOR_VICE_PRESIDENT', 'FOOD_DELIVERY_TRACKING', 'view_delivery_tracking', true),
  (gen_random_uuid()::text, 'SENIOR_VICE_PRESIDENT', 'FOOD_KITCHEN_SUMMARY', 'view_kitchen_summary', true),
  (gen_random_uuid()::text, 'SENIOR_VICE_PRESIDENT', 'FOOD_DISPATCH', 'view_dispatch_queue', true),
  (gen_random_uuid()::text, 'SENIOR_VICE_PRESIDENT', 'FOOD_CONFIRM_DELIVERY', 'view_deliveries', true),
  (gen_random_uuid()::text, 'SENIOR_VICE_PRESIDENT', 'FOOD_WASTE_TRACKING', 'view_waste_tracking', true),
  (gen_random_uuid()::text, 'SENIOR_VICE_PRESIDENT', 'FOOD_REPORTS', 'view_food_report', true),
  (gen_random_uuid()::text, 'SENIOR_VICE_PRESIDENT', 'FOOD_SETTINGS', 'view_food_setting', true),
  (gen_random_uuid()::text, 'SENIOR_VICE_PRESIDENT', 'FOOD_CATALOGUE', 'view_service_catalogue', true),
  (gen_random_uuid()::text, 'SENIOR_VICE_PRESIDENT', 'FOOD_ORG', 'view_kitchen_org', true),
  (gen_random_uuid()::text, 'SENIOR_VICE_PRESIDENT', 'AUDIT_DASHBOARD', 'view_audit_dashboard', true),
  (gen_random_uuid()::text, 'SENIOR_VICE_PRESIDENT', 'AUDIT_REGISTER', 'view_audit_register', true),
  (gen_random_uuid()::text, 'SENIOR_VICE_PRESIDENT', 'AUDIT_EXECUTION', 'view_audit', true),
  (gen_random_uuid()::text, 'SENIOR_VICE_PRESIDENT', 'AUDIT_REVIEW', 'view_review_queue', true),
  (gen_random_uuid()::text, 'SENIOR_VICE_PRESIDENT', 'AUDIT_REPORTS', 'view_audit_report', true),
  (gen_random_uuid()::text, 'SENIOR_VICE_PRESIDENT', 'AUDIT_SCHEDULES', 'view_schedule', true),
  (gen_random_uuid()::text, 'SENIOR_VICE_PRESIDENT', 'AUDIT_TEMPLATES', 'view_template', true),
  (gen_random_uuid()::text, 'SENIOR_VICE_PRESIDENT', 'AUDIT_ADMIN', 'view_audit_admin', true),
  (gen_random_uuid()::text, 'SENIOR_VICE_PRESIDENT', 'LEDGER', 'view_ledger', true),
  (gen_random_uuid()::text, 'SENIOR_VICE_PRESIDENT', 'PAYMENTS', 'view_payment', true),
  (gen_random_uuid()::text, 'SENIOR_VICE_PRESIDENT', 'WALLET', 'view_wallet', true),
  (gen_random_uuid()::text, 'SENIOR_VICE_PRESIDENT', 'BILLING_CYCLES', 'view_recurring_billing', true),
  (gen_random_uuid()::text, 'SENIOR_VICE_PRESIDENT', 'REMINDERS', 'view_reminder', true),
  (gen_random_uuid()::text, 'SENIOR_VICE_PRESIDENT', 'BANKING', 'view_banking', true),
  (gen_random_uuid()::text, 'SENIOR_VICE_PRESIDENT', 'EXPENSES', 'view_expense', true),
  (gen_random_uuid()::text, 'SENIOR_VICE_PRESIDENT', 'EMPLOYEES', 'view_employee', true),
  (gen_random_uuid()::text, 'SENIOR_VICE_PRESIDENT', 'RECRUITMENT', 'view_recruitment', true),
  (gen_random_uuid()::text, 'SENIOR_VICE_PRESIDENT', 'LND', 'view_learning_development', true),
  (gen_random_uuid()::text, 'SENIOR_VICE_PRESIDENT', 'VENDORS', 'view_vendor', true),
  (gen_random_uuid()::text, 'SENIOR_VICE_PRESIDENT', 'INDENTS', 'view_indent', true),
  (gen_random_uuid()::text, 'SENIOR_VICE_PRESIDENT', 'PURCHASE_ORDERS', 'view_purchase_order', true),
  (gen_random_uuid()::text, 'SENIOR_VICE_PRESIDENT', 'GRN', 'view_goods_received', true),
  (gen_random_uuid()::text, 'SENIOR_VICE_PRESIDENT', 'INVENTORY', 'view_inventory', true),
  (gen_random_uuid()::text, 'SENIOR_VICE_PRESIDENT', 'SALES_DASHBOARD', 'view_sales_dashboard', true),
  (gen_random_uuid()::text, 'SENIOR_VICE_PRESIDENT', 'SALES_LEADS', 'view_sales_crm', true),
  (gen_random_uuid()::text, 'SENIOR_VICE_PRESIDENT', 'PROPERTY_LEADS', 'view_property_lead', true),
  (gen_random_uuid()::text, 'SENIOR_VICE_PRESIDENT', 'USERS', 'view_user', true),
  (gen_random_uuid()::text, 'SENIOR_VICE_PRESIDENT', 'ACCESS_CONTROL', 'view_access', true),
  (gen_random_uuid()::text, 'SENIOR_VICE_PRESIDENT', 'SETTINGS', 'view_setting', true),
  (gen_random_uuid()::text, 'SENIOR_VICE_PRESIDENT', 'AUDIT_LOG', 'view_activity', true),
  (gen_random_uuid()::text, 'ZONAL_HEAD', 'FOOD_RECEIVE_UPDATE', 'view_receive_update', true),
  (gen_random_uuid()::text, 'ZONAL_HEAD', 'FOOD_DELIVERY_TRACKING', 'view_delivery_tracking', true),
  (gen_random_uuid()::text, 'ZONAL_HEAD', 'FOOD_DASHBOARD', 'view_food_dashboard', true),
  (gen_random_uuid()::text, 'ZONAL_HEAD', 'FOOD_ALL_ORDERS', 'view_order', true),
  (gen_random_uuid()::text, 'ZONAL_HEAD', 'FOOD_ALL_ORDERS', 'add_order', true),
  (gen_random_uuid()::text, 'ZONAL_HEAD', 'FOOD_ALL_ORDERS', 'edit_order', true),
  (gen_random_uuid()::text, 'ZONAL_HEAD', 'FOOD_ALL_ORDERS', 'delete_order', true),
  (gen_random_uuid()::text, 'ZONAL_HEAD', 'FOOD_PLACE_ORDER', 'view_order_form', true),
  (gen_random_uuid()::text, 'ZONAL_HEAD', 'FOOD_DISPATCH', 'view_dispatch_queue', true),
  (gen_random_uuid()::text, 'ZONAL_HEAD', 'FOOD_CONFIRM_DELIVERY', 'view_deliveries', true),
  (gen_random_uuid()::text, 'ZONAL_HEAD', 'FOOD_WASTE_TRACKING', 'view_waste_tracking', true),
  (gen_random_uuid()::text, 'ZONAL_HEAD', 'FOOD_REPORTS', 'view_food_report', true),
  (gen_random_uuid()::text, 'ZONAL_HEAD', 'AUDIT_DASHBOARD', 'view_audit_dashboard', true),
  (gen_random_uuid()::text, 'ZONAL_HEAD', 'AUDIT_REGISTER', 'view_audit_register', true),
  (gen_random_uuid()::text, 'ZONAL_HEAD', 'AUDIT_REPORTS', 'view_audit_report', true),
  (gen_random_uuid()::text, 'CITY_HEAD', 'FOOD_RECEIVE_UPDATE', 'view_receive_update', true),
  (gen_random_uuid()::text, 'CITY_HEAD', 'FOOD_DELIVERY_TRACKING', 'view_delivery_tracking', true),
  (gen_random_uuid()::text, 'CITY_HEAD', 'FOOD_DASHBOARD', 'view_food_dashboard', true),
  (gen_random_uuid()::text, 'CITY_HEAD', 'FOOD_ALL_ORDERS', 'view_order', true),
  (gen_random_uuid()::text, 'CITY_HEAD', 'FOOD_ALL_ORDERS', 'add_order', true),
  (gen_random_uuid()::text, 'CITY_HEAD', 'FOOD_ALL_ORDERS', 'edit_order', true),
  (gen_random_uuid()::text, 'CITY_HEAD', 'FOOD_ALL_ORDERS', 'delete_order', true),
  (gen_random_uuid()::text, 'CITY_HEAD', 'FOOD_PLACE_ORDER', 'view_order_form', true),
  (gen_random_uuid()::text, 'CITY_HEAD', 'FOOD_DISPATCH', 'view_dispatch_queue', true),
  (gen_random_uuid()::text, 'CITY_HEAD', 'FOOD_CONFIRM_DELIVERY', 'view_deliveries', true),
  (gen_random_uuid()::text, 'CITY_HEAD', 'FOOD_WASTE_TRACKING', 'view_waste_tracking', true),
  (gen_random_uuid()::text, 'CITY_HEAD', 'FOOD_REPORTS', 'view_food_report', true),
  (gen_random_uuid()::text, 'CITY_HEAD', 'AUDIT_DASHBOARD', 'view_audit_dashboard', true),
  (gen_random_uuid()::text, 'CITY_HEAD', 'AUDIT_REGISTER', 'view_audit_register', true),
  (gen_random_uuid()::text, 'CITY_HEAD', 'AUDIT_REPORTS', 'view_audit_report', true),
  (gen_random_uuid()::text, 'CLUSTER_MANAGER', 'FOOD_RECEIVE_UPDATE', 'view_receive_update', true),
  (gen_random_uuid()::text, 'CLUSTER_MANAGER', 'FOOD_RECEIVE_UPDATE', 'add_receive_update', true),
  (gen_random_uuid()::text, 'CLUSTER_MANAGER', 'FOOD_RECEIVE_UPDATE', 'edit_receive_update', true),
  (gen_random_uuid()::text, 'CLUSTER_MANAGER', 'FOOD_RECEIVE_UPDATE', 'delete_receive_update', true),
  (gen_random_uuid()::text, 'CLUSTER_MANAGER', 'FOOD_DELIVERY_TRACKING', 'view_delivery_tracking', true),
  (gen_random_uuid()::text, 'CLUSTER_MANAGER', 'FOOD_DELIVERY_TRACKING', 'add_delivery_tracking', true),
  (gen_random_uuid()::text, 'CLUSTER_MANAGER', 'FOOD_DELIVERY_TRACKING', 'edit_delivery_tracking', true),
  (gen_random_uuid()::text, 'CLUSTER_MANAGER', 'FOOD_DELIVERY_TRACKING', 'delete_delivery_tracking', true),
  (gen_random_uuid()::text, 'CLUSTER_MANAGER', 'FOOD_DASHBOARD', 'view_food_dashboard', true),
  (gen_random_uuid()::text, 'CLUSTER_MANAGER', 'FOOD_ALL_ORDERS', 'view_order', true),
  (gen_random_uuid()::text, 'CLUSTER_MANAGER', 'FOOD_ALL_ORDERS', 'add_order', true),
  (gen_random_uuid()::text, 'CLUSTER_MANAGER', 'FOOD_ALL_ORDERS', 'edit_order', true),
  (gen_random_uuid()::text, 'CLUSTER_MANAGER', 'FOOD_ALL_ORDERS', 'delete_order', true),
  (gen_random_uuid()::text, 'CLUSTER_MANAGER', 'FOOD_PLACE_ORDER', 'view_order_form', true),
  (gen_random_uuid()::text, 'CLUSTER_MANAGER', 'FOOD_PLACE_ORDER', 'draft_order', true),
  (gen_random_uuid()::text, 'CLUSTER_MANAGER', 'FOOD_PLACE_ORDER', 'edit_order', true),
  (gen_random_uuid()::text, 'CLUSTER_MANAGER', 'FOOD_PLACE_ORDER', 'cancel_draft', true),
  (gen_random_uuid()::text, 'CLUSTER_MANAGER', 'FOOD_PLACE_ORDER', 'place_order', true),
  (gen_random_uuid()::text, 'CLUSTER_MANAGER', 'FOOD_DISPATCH', 'view_dispatch_queue', true),
  (gen_random_uuid()::text, 'CLUSTER_MANAGER', 'FOOD_CONFIRM_DELIVERY', 'view_deliveries', true),
  (gen_random_uuid()::text, 'CLUSTER_MANAGER', 'FOOD_CONFIRM_DELIVERY', 'amend_delivery', true),
  (gen_random_uuid()::text, 'CLUSTER_MANAGER', 'FOOD_CONFIRM_DELIVERY', 'confirm_receipt', true),
  (gen_random_uuid()::text, 'CLUSTER_MANAGER', 'FOOD_WASTE_TRACKING', 'view_waste_tracking', true),
  (gen_random_uuid()::text, 'CLUSTER_MANAGER', 'FOOD_WASTE_TRACKING', 'add_waste_tracking', true),
  (gen_random_uuid()::text, 'CLUSTER_MANAGER', 'FOOD_WASTE_TRACKING', 'edit_waste_tracking', true),
  (gen_random_uuid()::text, 'CLUSTER_MANAGER', 'FOOD_WASTE_TRACKING', 'delete_waste_tracking', true),
  (gen_random_uuid()::text, 'CLUSTER_MANAGER', 'FOOD_REPORTS', 'view_food_report', true),
  (gen_random_uuid()::text, 'CLUSTER_MANAGER', 'AUDIT_DASHBOARD', 'view_audit_dashboard', true),
  (gen_random_uuid()::text, 'CLUSTER_MANAGER', 'AUDIT_REGISTER', 'view_audit_register', true),
  (gen_random_uuid()::text, 'CLUSTER_MANAGER', 'AUDIT_REPORTS', 'view_audit_report', true),
  (gen_random_uuid()::text, 'CLUSTER_MANAGER', 'AUDIT_EXECUTION', 'view_audit', true),
  (gen_random_uuid()::text, 'CLUSTER_MANAGER', 'AUDIT_EXECUTION', 'record_answers', true),
  (gen_random_uuid()::text, 'UNIT_LEAD', 'FOOD_RECEIVE_UPDATE', 'view_receive_update', true),
  (gen_random_uuid()::text, 'UNIT_LEAD', 'FOOD_RECEIVE_UPDATE', 'add_receive_update', true),
  (gen_random_uuid()::text, 'UNIT_LEAD', 'FOOD_RECEIVE_UPDATE', 'edit_receive_update', true),
  (gen_random_uuid()::text, 'UNIT_LEAD', 'FOOD_RECEIVE_UPDATE', 'delete_receive_update', true),
  (gen_random_uuid()::text, 'UNIT_LEAD', 'FOOD_DELIVERY_TRACKING', 'view_delivery_tracking', true),
  (gen_random_uuid()::text, 'UNIT_LEAD', 'FOOD_DELIVERY_TRACKING', 'add_delivery_tracking', true),
  (gen_random_uuid()::text, 'UNIT_LEAD', 'FOOD_DELIVERY_TRACKING', 'edit_delivery_tracking', true),
  (gen_random_uuid()::text, 'UNIT_LEAD', 'FOOD_DELIVERY_TRACKING', 'delete_delivery_tracking', true),
  (gen_random_uuid()::text, 'UNIT_LEAD', 'FOOD_DASHBOARD', 'view_food_dashboard', true),
  (gen_random_uuid()::text, 'UNIT_LEAD', 'FOOD_ALL_ORDERS', 'view_order', true),
  (gen_random_uuid()::text, 'UNIT_LEAD', 'FOOD_PLACE_ORDER', 'view_order_form', true),
  (gen_random_uuid()::text, 'UNIT_LEAD', 'FOOD_PLACE_ORDER', 'draft_order', true),
  (gen_random_uuid()::text, 'UNIT_LEAD', 'FOOD_PLACE_ORDER', 'edit_order', true),
  (gen_random_uuid()::text, 'UNIT_LEAD', 'FOOD_PLACE_ORDER', 'cancel_draft', true),
  (gen_random_uuid()::text, 'UNIT_LEAD', 'FOOD_PLACE_ORDER', 'place_order', true),
  (gen_random_uuid()::text, 'UNIT_LEAD', 'FOOD_CONFIRM_DELIVERY', 'view_deliveries', true),
  (gen_random_uuid()::text, 'UNIT_LEAD', 'FOOD_CONFIRM_DELIVERY', 'amend_delivery', true),
  (gen_random_uuid()::text, 'UNIT_LEAD', 'FOOD_CONFIRM_DELIVERY', 'confirm_receipt', true),
  (gen_random_uuid()::text, 'UNIT_LEAD', 'FOOD_WASTE_TRACKING', 'view_waste_tracking', true),
  (gen_random_uuid()::text, 'UNIT_LEAD', 'FOOD_WASTE_TRACKING', 'add_waste_tracking', true),
  (gen_random_uuid()::text, 'UNIT_LEAD', 'FOOD_WASTE_TRACKING', 'edit_waste_tracking', true),
  (gen_random_uuid()::text, 'UNIT_LEAD', 'FOOD_WASTE_TRACKING', 'delete_waste_tracking', true),
  (gen_random_uuid()::text, 'UNIT_LEAD', 'FOOD_REPORTS', 'view_food_report', true),
  (gen_random_uuid()::text, 'UNIT_LEAD', 'AUDIT_DASHBOARD', 'view_audit_dashboard', true),
  (gen_random_uuid()::text, 'UNIT_LEAD', 'AUDIT_REGISTER', 'view_audit_register', true),
  (gen_random_uuid()::text, 'UNIT_LEAD', 'AUDIT_REPORTS', 'view_audit_report', true),
  (gen_random_uuid()::text, 'UNIT_LEAD', 'AUDIT_EXECUTION', 'view_audit', true),
  (gen_random_uuid()::text, 'UNIT_LEAD', 'AUDIT_EXECUTION', 'record_answers', true),
  (gen_random_uuid()::text, 'UNIT_LEAD', 'DASHBOARD', 'view_dashboard', true),
  (gen_random_uuid()::text, 'UNIT_LEAD', 'PROPERTIES', 'view_property', true),
  (gen_random_uuid()::text, 'UNIT_LEAD', 'RESIDENTS', 'view_resident', true),
  (gen_random_uuid()::text, 'UNIT_LEAD', 'RESIDENTS', 'add_resident', true),
  (gen_random_uuid()::text, 'UNIT_LEAD', 'RESIDENTS', 'edit_resident', true),
  (gen_random_uuid()::text, 'UNIT_LEAD', 'RESIDENTS', 'delete_resident', true),
  (gen_random_uuid()::text, 'UNIT_LEAD', 'RESIDENTS', 'export_resident', true),
  (gen_random_uuid()::text, 'UNIT_LEAD', 'COMPLAINT_TICKETS', 'view_complaint', true),
  (gen_random_uuid()::text, 'UNIT_LEAD', 'COMPLAINT_TICKETS', 'add_complaint', true),
  (gen_random_uuid()::text, 'UNIT_LEAD', 'COMPLAINT_TICKETS', 'edit_complaint', true),
  (gen_random_uuid()::text, 'UNIT_LEAD', 'COMPLAINT_TICKETS', 'delete_complaint', true),
  (gen_random_uuid()::text, 'UNIT_LEAD', 'COMPLAINT_TICKETS', 'assign_complaint', true),
  (gen_random_uuid()::text, 'UNIT_LEAD', 'COMPLAINT_TICKETS', 'close_complaint', true),
  (gen_random_uuid()::text, 'UNIT_LEAD', 'COMPLAINT_TICKETS', 'verify_complaint', true),
  (gen_random_uuid()::text, 'UNIT_LEAD', 'LAUNDRY_BATCHES', 'view_laundry_batche', true),
  (gen_random_uuid()::text, 'UNIT_LEAD', 'LAUNDRY_BATCHES', 'add_laundry_batche', true),
  (gen_random_uuid()::text, 'UNIT_LEAD', 'LAUNDRY_BATCHES', 'edit_laundry_batche', true),
  (gen_random_uuid()::text, 'UNIT_LEAD', 'LAUNDRY_BATCHES', 'delete_laundry_batche', true),
  (gen_random_uuid()::text, 'UNIT_LEAD', 'COMMUNICATIONS', 'view_communication', true),
  (gen_random_uuid()::text, 'UNIT_LEAD', 'COMMUNICATIONS', 'add_communication', true),
  (gen_random_uuid()::text, 'UNIT_LEAD', 'RESIDENT_ATTENDANCE', 'view_resident_attendance', true),
  (gen_random_uuid()::text, 'UNIT_LEAD', 'RESIDENT_ATTENDANCE', 'add_resident_attendance', true),
  (gen_random_uuid()::text, 'UNIT_LEAD', 'RESIDENT_ATTENDANCE', 'edit_resident_attendance', true),
  (gen_random_uuid()::text, 'UNIT_LEAD', 'RESIDENT_ATTENDANCE', 'delete_resident_attendance', true),
  (gen_random_uuid()::text, 'UNIT_LEAD', 'FACILITY', 'view_facility', true),
  (gen_random_uuid()::text, 'UNIT_LEAD', 'ELECTRICITY', 'view_electricity', true),
  (gen_random_uuid()::text, 'UNIT_LEAD', 'IOT', 'view_iot', true),
  (gen_random_uuid()::text, 'UNIT_LEAD', 'WALLET', 'view_wallet', true),
  (gen_random_uuid()::text, 'RM_MANAGER', 'DASHBOARD', 'view_dashboard', true),
  (gen_random_uuid()::text, 'RM_MANAGER', 'PROPERTIES', 'view_property', true),
  (gen_random_uuid()::text, 'RM_MANAGER', 'RESIDENTS', 'view_resident', true),
  (gen_random_uuid()::text, 'RM_MANAGER', 'COMPLAINT_TICKETS', 'view_complaint', true),
  (gen_random_uuid()::text, 'RM_MANAGER', 'COMPLAINT_TICKETS', 'add_complaint', true),
  (gen_random_uuid()::text, 'RM_MANAGER', 'COMPLAINT_TICKETS', 'edit_complaint', true),
  (gen_random_uuid()::text, 'RM_MANAGER', 'COMPLAINT_TICKETS', 'delete_complaint', true),
  (gen_random_uuid()::text, 'RM_MANAGER', 'COMPLAINT_TICKETS', 'assign_complaint', true),
  (gen_random_uuid()::text, 'RM_MANAGER', 'COMPLAINT_TICKETS', 'close_complaint', true),
  (gen_random_uuid()::text, 'RM_MANAGER', 'COMPLAINT_TICKETS', 'verify_complaint', true),
  (gen_random_uuid()::text, 'RM_MANAGER', 'COMPLAINT_ROUTING', 'view_routing_sla', true),
  (gen_random_uuid()::text, 'RM_MANAGER', 'COMPLAINT_ROUTING', 'add_routing_sla', true),
  (gen_random_uuid()::text, 'RM_MANAGER', 'COMPLAINT_ROUTING', 'edit_routing_sla', true),
  (gen_random_uuid()::text, 'RM_MANAGER', 'COMPLAINT_ROUTING', 'delete_routing_sla', true),
  (gen_random_uuid()::text, 'RM_MANAGER', 'COMPLAINT_ROUTING', 'configure_routing_sla', true),
  (gen_random_uuid()::text, 'RM_MANAGER', 'COMMUNICATIONS', 'view_communication', true),
  (gen_random_uuid()::text, 'RM_SUPERVISOR', 'DASHBOARD', 'view_dashboard', true),
  (gen_random_uuid()::text, 'RM_SUPERVISOR', 'PROPERTIES', 'view_property', true),
  (gen_random_uuid()::text, 'RM_SUPERVISOR', 'RESIDENTS', 'view_resident', true),
  (gen_random_uuid()::text, 'RM_SUPERVISOR', 'COMPLAINT_TICKETS', 'view_complaint', true),
  (gen_random_uuid()::text, 'RM_SUPERVISOR', 'COMPLAINT_TICKETS', 'add_complaint', true),
  (gen_random_uuid()::text, 'RM_SUPERVISOR', 'COMPLAINT_TICKETS', 'edit_complaint', true),
  (gen_random_uuid()::text, 'RM_SUPERVISOR', 'COMPLAINT_TICKETS', 'assign_complaint', true),
  (gen_random_uuid()::text, 'RM_SUPERVISOR', 'COMPLAINT_TICKETS', 'close_complaint', true),
  (gen_random_uuid()::text, 'RM_SUPERVISOR', 'COMPLAINT_TICKETS', 'verify_complaint', true),
  (gen_random_uuid()::text, 'HOUSEKEEPING_MANAGER', 'DASHBOARD', 'view_dashboard', true),
  (gen_random_uuid()::text, 'HOUSEKEEPING_MANAGER', 'PROPERTIES', 'view_property', true),
  (gen_random_uuid()::text, 'HOUSEKEEPING_MANAGER', 'RESIDENTS', 'view_resident', true),
  (gen_random_uuid()::text, 'HOUSEKEEPING_MANAGER', 'COMPLAINT_TICKETS', 'view_complaint', true),
  (gen_random_uuid()::text, 'HOUSEKEEPING_MANAGER', 'COMPLAINT_TICKETS', 'add_complaint', true),
  (gen_random_uuid()::text, 'HOUSEKEEPING_MANAGER', 'COMPLAINT_TICKETS', 'edit_complaint', true),
  (gen_random_uuid()::text, 'HOUSEKEEPING_MANAGER', 'COMPLAINT_TICKETS', 'delete_complaint', true),
  (gen_random_uuid()::text, 'HOUSEKEEPING_MANAGER', 'COMPLAINT_TICKETS', 'assign_complaint', true),
  (gen_random_uuid()::text, 'HOUSEKEEPING_MANAGER', 'COMPLAINT_TICKETS', 'close_complaint', true),
  (gen_random_uuid()::text, 'HOUSEKEEPING_MANAGER', 'COMPLAINT_TICKETS', 'verify_complaint', true),
  (gen_random_uuid()::text, 'HOUSEKEEPING_MANAGER', 'COMPLAINT_ROUTING', 'view_routing_sla', true),
  (gen_random_uuid()::text, 'HOUSEKEEPING_MANAGER', 'COMPLAINT_ROUTING', 'add_routing_sla', true),
  (gen_random_uuid()::text, 'HOUSEKEEPING_MANAGER', 'COMPLAINT_ROUTING', 'edit_routing_sla', true),
  (gen_random_uuid()::text, 'HOUSEKEEPING_MANAGER', 'COMPLAINT_ROUTING', 'delete_routing_sla', true),
  (gen_random_uuid()::text, 'HOUSEKEEPING_MANAGER', 'COMPLAINT_ROUTING', 'configure_routing_sla', true),
  (gen_random_uuid()::text, 'HOUSEKEEPING_MANAGER', 'COMMUNICATIONS', 'view_communication', true),
  (gen_random_uuid()::text, 'HOUSEKEEPING_SUPERVISOR', 'DASHBOARD', 'view_dashboard', true),
  (gen_random_uuid()::text, 'HOUSEKEEPING_SUPERVISOR', 'PROPERTIES', 'view_property', true),
  (gen_random_uuid()::text, 'HOUSEKEEPING_SUPERVISOR', 'RESIDENTS', 'view_resident', true),
  (gen_random_uuid()::text, 'HOUSEKEEPING_SUPERVISOR', 'COMPLAINT_TICKETS', 'view_complaint', true),
  (gen_random_uuid()::text, 'HOUSEKEEPING_SUPERVISOR', 'COMPLAINT_TICKETS', 'add_complaint', true),
  (gen_random_uuid()::text, 'HOUSEKEEPING_SUPERVISOR', 'COMPLAINT_TICKETS', 'edit_complaint', true),
  (gen_random_uuid()::text, 'HOUSEKEEPING_SUPERVISOR', 'COMPLAINT_TICKETS', 'assign_complaint', true),
  (gen_random_uuid()::text, 'HOUSEKEEPING_SUPERVISOR', 'COMPLAINT_TICKETS', 'close_complaint', true),
  (gen_random_uuid()::text, 'HOUSEKEEPING_SUPERVISOR', 'COMPLAINT_TICKETS', 'verify_complaint', true),
  (gen_random_uuid()::text, 'CUSTOMER_EXPERIENCE', 'COMPLAINT_TICKETS', 'view_complaint', true),
  (gen_random_uuid()::text, 'CUSTOMER_EXPERIENCE', 'COMPLAINT_TICKETS', 'add_complaint', true),
  (gen_random_uuid()::text, 'CUSTOMER_EXPERIENCE', 'COMPLAINT_TICKETS', 'edit_complaint', true),
  (gen_random_uuid()::text, 'CUSTOMER_EXPERIENCE', 'COMPLAINT_TICKETS', 'delete_complaint', true),
  (gen_random_uuid()::text, 'CUSTOMER_EXPERIENCE', 'COMPLAINT_TICKETS', 'assign_complaint', true),
  (gen_random_uuid()::text, 'CUSTOMER_EXPERIENCE', 'COMPLAINT_TICKETS', 'close_complaint', true),
  (gen_random_uuid()::text, 'CUSTOMER_EXPERIENCE', 'COMPLAINT_TICKETS', 'verify_complaint', true),
  (gen_random_uuid()::text, 'CUSTOMER_EXPERIENCE', 'COMPLAINT_ROUTING', 'view_routing_sla', true),
  (gen_random_uuid()::text, 'CUSTOMER_EXPERIENCE', 'COMPLAINT_ROUTING', 'add_routing_sla', true),
  (gen_random_uuid()::text, 'CUSTOMER_EXPERIENCE', 'COMPLAINT_ROUTING', 'edit_routing_sla', true),
  (gen_random_uuid()::text, 'CUSTOMER_EXPERIENCE', 'COMPLAINT_ROUTING', 'delete_routing_sla', true),
  (gen_random_uuid()::text, 'CUSTOMER_EXPERIENCE', 'COMPLAINT_ROUTING', 'configure_routing_sla', true),
  (gen_random_uuid()::text, 'CUSTOMER_EXPERIENCE', 'RESIDENTS', 'view_resident', true),
  (gen_random_uuid()::text, 'CUSTOMER_EXPERIENCE', 'PROPERTIES', 'view_property', true),
  (gen_random_uuid()::text, 'CUSTOMER_EXPERIENCE', 'COMMUNICATIONS', 'view_communication', true),
  (gen_random_uuid()::text, 'CUSTOMER_EXPERIENCE', 'COMMUNICATIONS', 'add_communication', true),
  (gen_random_uuid()::text, 'CUSTOMER_EXPERIENCE', 'COMMUNICATIONS', 'edit_communication', true),
  (gen_random_uuid()::text, 'CUSTOMER_EXPERIENCE', 'COMMUNICATIONS', 'delete_communication', true),
  (gen_random_uuid()::text, 'CUSTOMER_EXPERIENCE', 'DASHBOARD', 'view_dashboard', true),
  (gen_random_uuid()::text, 'CUSTOMER_EXPERIENCE', 'AUDIT_DASHBOARD', 'view_audit_dashboard', true),
  (gen_random_uuid()::text, 'CUSTOMER_EXPERIENCE', 'AUDIT_REGISTER', 'view_audit_register', true),
  (gen_random_uuid()::text, 'CUSTOMER_EXPERIENCE', 'AUDIT_REPORTS', 'view_audit_report', true),
  (gen_random_uuid()::text, 'CUSTOMER_EXPERIENCE', 'AUDIT_EXECUTION', 'view_audit', true),
  (gen_random_uuid()::text, 'CUSTOMER_EXPERIENCE', 'AUDIT_EXECUTION', 'start_audit', true),
  (gen_random_uuid()::text, 'CUSTOMER_EXPERIENCE', 'AUDIT_EXECUTION', 'record_answers', true),
  (gen_random_uuid()::text, 'CARE_DESK_AGENT', 'DASHBOARD', 'view_dashboard', true),
  (gen_random_uuid()::text, 'CARE_DESK_AGENT', 'PROPERTIES', 'view_property', true),
  (gen_random_uuid()::text, 'CARE_DESK_AGENT', 'RESIDENTS', 'view_resident', true),
  (gen_random_uuid()::text, 'CARE_DESK_AGENT', 'COMMUNICATIONS', 'view_communication', true),
  (gen_random_uuid()::text, 'CARE_DESK_AGENT', 'COMPLAINT_TICKETS', 'view_complaint', true),
  (gen_random_uuid()::text, 'CARE_DESK_AGENT', 'COMPLAINT_TICKETS', 'add_complaint', true),
  (gen_random_uuid()::text, 'CARE_DESK_AGENT', 'COMPLAINT_TICKETS', 'edit_complaint', true),
  (gen_random_uuid()::text, 'CARE_DESK_AGENT', 'COMPLAINT_TICKETS', 'assign_complaint', true),
  (gen_random_uuid()::text, 'CARE_DESK_AGENT', 'AUDIT_REGISTER', 'view_audit_register', true),
  (gen_random_uuid()::text, 'FNB_MANAGER', 'FOOD_DELIVERY_TRACKING', 'view_delivery_tracking', true),
  (gen_random_uuid()::text, 'FNB_MANAGER', 'FOOD_DASHBOARD', 'view_food_dashboard', true),
  (gen_random_uuid()::text, 'FNB_MANAGER', 'FOOD_PLACE_ORDER', 'view_order_form', true),
  (gen_random_uuid()::text, 'FNB_MANAGER', 'FOOD_KITCHEN_SUMMARY', 'view_kitchen_summary', true),
  (gen_random_uuid()::text, 'FNB_MANAGER', 'FOOD_KITCHEN_SUMMARY', 'add_kitchen_summary', true),
  (gen_random_uuid()::text, 'FNB_MANAGER', 'FOOD_KITCHEN_SUMMARY', 'edit_kitchen_summary', true),
  (gen_random_uuid()::text, 'FNB_MANAGER', 'FOOD_KITCHEN_SUMMARY', 'delete_kitchen_summary', true),
  (gen_random_uuid()::text, 'FNB_MANAGER', 'FOOD_DISPATCH', 'view_dispatch_queue', true),
  (gen_random_uuid()::text, 'FNB_MANAGER', 'FOOD_DISPATCH', 'edit_dispatch', true),
  (gen_random_uuid()::text, 'FNB_MANAGER', 'FOOD_DISPATCH', 'assign_rider', true),
  (gen_random_uuid()::text, 'FNB_MANAGER', 'FOOD_DISPATCH', 'mark_dispatched', true),
  (gen_random_uuid()::text, 'FNB_MANAGER', 'FOOD_CONFIRM_DELIVERY', 'view_deliveries', true),
  (gen_random_uuid()::text, 'FNB_MANAGER', 'FOOD_WASTE_TRACKING', 'view_waste_tracking', true),
  (gen_random_uuid()::text, 'FNB_MANAGER', 'FOOD_REPORTS', 'view_food_report', true),
  (gen_random_uuid()::text, 'FNB_MANAGER', 'FOOD_SETTINGS', 'view_food_setting', true),
  (gen_random_uuid()::text, 'FNB_MANAGER', 'FOOD_SETTINGS', 'add_food_setting', true),
  (gen_random_uuid()::text, 'FNB_MANAGER', 'FOOD_SETTINGS', 'edit_food_setting', true),
  (gen_random_uuid()::text, 'FNB_MANAGER', 'FOOD_SETTINGS', 'delete_food_setting', true),
  (gen_random_uuid()::text, 'FNB_MANAGER', 'FOOD_SETTINGS', 'configure_food_setting', true),
  (gen_random_uuid()::text, 'FNB_SUPERVISOR', 'FOOD_DELIVERY_TRACKING', 'view_delivery_tracking', true),
  (gen_random_uuid()::text, 'FNB_SUPERVISOR', 'FOOD_DASHBOARD', 'view_food_dashboard', true),
  (gen_random_uuid()::text, 'FNB_SUPERVISOR', 'FOOD_PLACE_ORDER', 'view_order_form', true),
  (gen_random_uuid()::text, 'FNB_SUPERVISOR', 'FOOD_KITCHEN_SUMMARY', 'view_kitchen_summary', true),
  (gen_random_uuid()::text, 'FNB_SUPERVISOR', 'FOOD_KITCHEN_SUMMARY', 'add_kitchen_summary', true),
  (gen_random_uuid()::text, 'FNB_SUPERVISOR', 'FOOD_KITCHEN_SUMMARY', 'edit_kitchen_summary', true),
  (gen_random_uuid()::text, 'FNB_SUPERVISOR', 'FOOD_KITCHEN_SUMMARY', 'delete_kitchen_summary', true),
  (gen_random_uuid()::text, 'FNB_SUPERVISOR', 'FOOD_DISPATCH', 'view_dispatch_queue', true),
  (gen_random_uuid()::text, 'FNB_SUPERVISOR', 'FOOD_DISPATCH', 'edit_dispatch', true),
  (gen_random_uuid()::text, 'FNB_SUPERVISOR', 'FOOD_DISPATCH', 'assign_rider', true),
  (gen_random_uuid()::text, 'FNB_SUPERVISOR', 'FOOD_DISPATCH', 'mark_dispatched', true),
  (gen_random_uuid()::text, 'FNB_SUPERVISOR', 'FOOD_CONFIRM_DELIVERY', 'view_deliveries', true),
  (gen_random_uuid()::text, 'FNB_SUPERVISOR', 'FOOD_WASTE_TRACKING', 'view_waste_tracking', true),
  (gen_random_uuid()::text, 'FNB_SUPERVISOR', 'FOOD_REPORTS', 'view_food_report', true),
  (gen_random_uuid()::text, 'KITCHEN_MANAGER', 'DASHBOARD', 'view_dashboard', true),
  (gen_random_uuid()::text, 'KITCHEN_MANAGER', 'INVENTORY', 'view_inventory', true),
  (gen_random_uuid()::text, 'KITCHEN_MANAGER', 'INVENTORY', 'add_inventory', true),
  (gen_random_uuid()::text, 'KITCHEN_MANAGER', 'INVENTORY', 'edit_inventory', true),
  (gen_random_uuid()::text, 'KITCHEN_MANAGER', 'INVENTORY', 'delete_inventory', true),
  (gen_random_uuid()::text, 'KITCHEN_MANAGER', 'INDENTS', 'view_indent', true),
  (gen_random_uuid()::text, 'KITCHEN_MANAGER', 'INDENTS', 'add_indent', true),
  (gen_random_uuid()::text, 'KITCHEN_MANAGER', 'INDENTS', 'edit_indent', true),
  (gen_random_uuid()::text, 'KITCHEN_MANAGER', 'INDENTS', 'delete_indent', true),
  (gen_random_uuid()::text, 'KITCHEN_MANAGER', 'INDENTS', 'submit_indent', true),
  (gen_random_uuid()::text, 'KITCHEN_MANAGER', 'INDENTS', 'approve_indent', true),
  (gen_random_uuid()::text, 'KITCHEN_MANAGER', 'INDENTS', 'reject_indent', true),
  (gen_random_uuid()::text, 'KITCHEN_MANAGER', 'GRN', 'view_goods_received', true),
  (gen_random_uuid()::text, 'KITCHEN_MANAGER', 'GRN', 'add_goods_received', true),
  (gen_random_uuid()::text, 'KITCHEN_MANAGER', 'GRN', 'edit_goods_received', true),
  (gen_random_uuid()::text, 'KITCHEN_MANAGER', 'GRN', 'delete_goods_received', true),
  (gen_random_uuid()::text, 'KITCHEN_MANAGER', 'FOOD_KITCHEN_SUMMARY', 'view_kitchen_summary', true),
  (gen_random_uuid()::text, 'KITCHEN_MANAGER', 'FOOD_RECEIVE_UPDATE', 'view_receive_update', true),
  (gen_random_uuid()::text, 'KITCHEN_MANAGER', 'FOOD_RECEIVE_UPDATE', 'add_receive_update', true),
  (gen_random_uuid()::text, 'KITCHEN_MANAGER', 'FOOD_RECEIVE_UPDATE', 'edit_receive_update', true),
  (gen_random_uuid()::text, 'KITCHEN_MANAGER', 'FOOD_RECEIVE_UPDATE', 'delete_receive_update', true),
  (gen_random_uuid()::text, 'KITCHEN_MANAGER', 'FOOD_WASTE_TRACKING', 'view_waste_tracking', true),
  (gen_random_uuid()::text, 'KITCHEN_MANAGER', 'FOOD_WASTE_TRACKING', 'add_waste_tracking', true),
  (gen_random_uuid()::text, 'KITCHEN_MANAGER', 'FOOD_WASTE_TRACKING', 'edit_waste_tracking', true),
  (gen_random_uuid()::text, 'KITCHEN_MANAGER', 'FOOD_WASTE_TRACKING', 'delete_waste_tracking', true),
  (gen_random_uuid()::text, 'FINANCE', 'DASHBOARD', 'view_dashboard', true),
  (gen_random_uuid()::text, 'FINANCE', 'EXECUTIVE_DASHBOARD', 'view_executive_dashboard', true),
  (gen_random_uuid()::text, 'FINANCE', 'RESIDENTS', 'view_resident', true),
  (gen_random_uuid()::text, 'FINANCE', 'LEDGER', 'view_ledger', true),
  (gen_random_uuid()::text, 'FINANCE', 'LEDGER', 'add_ledger', true),
  (gen_random_uuid()::text, 'FINANCE', 'LEDGER', 'edit_ledger', true),
  (gen_random_uuid()::text, 'FINANCE', 'LEDGER', 'delete_ledger', true),
  (gen_random_uuid()::text, 'FINANCE', 'PAYMENTS', 'view_payment', true),
  (gen_random_uuid()::text, 'FINANCE', 'PAYMENTS', 'add_payment', true),
  (gen_random_uuid()::text, 'FINANCE', 'PAYMENTS', 'edit_payment', true),
  (gen_random_uuid()::text, 'FINANCE', 'PAYMENTS', 'delete_payment', true),
  (gen_random_uuid()::text, 'FINANCE', 'PAYMENTS', 'approve_payment', true),
  (gen_random_uuid()::text, 'FINANCE', 'PAYMENTS', 'verify_payment', true),
  (gen_random_uuid()::text, 'FINANCE', 'WALLET', 'view_wallet', true),
  (gen_random_uuid()::text, 'FINANCE', 'WALLET', 'add_wallet', true),
  (gen_random_uuid()::text, 'FINANCE', 'WALLET', 'edit_wallet', true),
  (gen_random_uuid()::text, 'FINANCE', 'WALLET', 'delete_wallet', true),
  (gen_random_uuid()::text, 'FINANCE', 'WALLET', 'approve_wallet', true),
  (gen_random_uuid()::text, 'FINANCE', 'WALLET', 'verify_wallet', true),
  (gen_random_uuid()::text, 'FINANCE', 'BILLING_CYCLES', 'view_recurring_billing', true),
  (gen_random_uuid()::text, 'FINANCE', 'BILLING_CYCLES', 'add_recurring_billing', true),
  (gen_random_uuid()::text, 'FINANCE', 'BILLING_CYCLES', 'edit_recurring_billing', true),
  (gen_random_uuid()::text, 'FINANCE', 'BILLING_CYCLES', 'delete_recurring_billing', true),
  (gen_random_uuid()::text, 'FINANCE', 'REMINDERS', 'view_reminder', true),
  (gen_random_uuid()::text, 'FINANCE', 'REMINDERS', 'add_reminder', true),
  (gen_random_uuid()::text, 'FINANCE', 'REMINDERS', 'edit_reminder', true),
  (gen_random_uuid()::text, 'FINANCE', 'REMINDERS', 'delete_reminder', true),
  (gen_random_uuid()::text, 'FINANCE', 'BANKING', 'view_banking', true),
  (gen_random_uuid()::text, 'FINANCE', 'BANKING', 'add_banking', true),
  (gen_random_uuid()::text, 'FINANCE', 'BANKING', 'edit_banking', true),
  (gen_random_uuid()::text, 'FINANCE', 'BANKING', 'delete_banking', true),
  (gen_random_uuid()::text, 'FINANCE', 'EXPENSES', 'view_expense', true),
  (gen_random_uuid()::text, 'FINANCE', 'EXPENSES', 'add_expense', true),
  (gen_random_uuid()::text, 'FINANCE', 'EXPENSES', 'edit_expense', true),
  (gen_random_uuid()::text, 'FINANCE', 'EXPENSES', 'delete_expense', true),
  (gen_random_uuid()::text, 'FINANCE', 'EXPENSES', 'submit_expense', true),
  (gen_random_uuid()::text, 'FINANCE', 'EXPENSES', 'approve_expense', true),
  (gen_random_uuid()::text, 'FINANCE', 'EXPENSES', 'reject_expense', true),
  (gen_random_uuid()::text, 'FINANCE', 'INDENTS', 'view_indent', true),
  (gen_random_uuid()::text, 'FINANCE', 'PURCHASE_ORDERS', 'view_purchase_order', true),
  (gen_random_uuid()::text, 'FINANCE_EXECUTIVE', 'DASHBOARD', 'view_dashboard', true),
  (gen_random_uuid()::text, 'FINANCE_EXECUTIVE', 'EXECUTIVE_DASHBOARD', 'view_executive_dashboard', true),
  (gen_random_uuid()::text, 'FINANCE_EXECUTIVE', 'RESIDENTS', 'view_resident', true),
  (gen_random_uuid()::text, 'FINANCE_EXECUTIVE', 'LEDGER', 'view_ledger', true),
  (gen_random_uuid()::text, 'FINANCE_EXECUTIVE', 'LEDGER', 'add_ledger', true),
  (gen_random_uuid()::text, 'FINANCE_EXECUTIVE', 'LEDGER', 'edit_ledger', true),
  (gen_random_uuid()::text, 'FINANCE_EXECUTIVE', 'PAYMENTS', 'view_payment', true),
  (gen_random_uuid()::text, 'FINANCE_EXECUTIVE', 'PAYMENTS', 'add_payment', true),
  (gen_random_uuid()::text, 'FINANCE_EXECUTIVE', 'PAYMENTS', 'edit_payment', true),
  (gen_random_uuid()::text, 'FINANCE_EXECUTIVE', 'PAYMENTS', 'verify_payment', true),
  (gen_random_uuid()::text, 'FINANCE_EXECUTIVE', 'EXPENSES', 'view_expense', true),
  (gen_random_uuid()::text, 'FINANCE_EXECUTIVE', 'EXPENSES', 'add_expense', true),
  (gen_random_uuid()::text, 'FINANCE_EXECUTIVE', 'EXPENSES', 'edit_expense', true),
  (gen_random_uuid()::text, 'FINANCE_EXECUTIVE', 'EXPENSES', 'submit_expense', true),
  (gen_random_uuid()::text, 'FINANCE_EXECUTIVE', 'WALLET', 'view_wallet', true),
  (gen_random_uuid()::text, 'FINANCE_EXECUTIVE', 'BANKING', 'view_banking', true),
  (gen_random_uuid()::text, 'FINANCE_EXECUTIVE', 'BILLING_CYCLES', 'view_recurring_billing', true),
  (gen_random_uuid()::text, 'FINANCE_EXECUTIVE', 'REMINDERS', 'view_reminder', true),
  (gen_random_uuid()::text, 'PROCUREMENT_MANAGER', 'DASHBOARD', 'view_dashboard', true),
  (gen_random_uuid()::text, 'PROCUREMENT_MANAGER', 'VENDORS', 'view_vendor', true),
  (gen_random_uuid()::text, 'PROCUREMENT_MANAGER', 'VENDORS', 'add_vendor', true),
  (gen_random_uuid()::text, 'PROCUREMENT_MANAGER', 'VENDORS', 'edit_vendor', true),
  (gen_random_uuid()::text, 'PROCUREMENT_MANAGER', 'VENDORS', 'delete_vendor', true),
  (gen_random_uuid()::text, 'PROCUREMENT_MANAGER', 'INDENTS', 'view_indent', true),
  (gen_random_uuid()::text, 'PROCUREMENT_MANAGER', 'INDENTS', 'add_indent', true),
  (gen_random_uuid()::text, 'PROCUREMENT_MANAGER', 'INDENTS', 'edit_indent', true),
  (gen_random_uuid()::text, 'PROCUREMENT_MANAGER', 'INDENTS', 'delete_indent', true),
  (gen_random_uuid()::text, 'PROCUREMENT_MANAGER', 'INDENTS', 'submit_indent', true),
  (gen_random_uuid()::text, 'PROCUREMENT_MANAGER', 'INDENTS', 'approve_indent', true),
  (gen_random_uuid()::text, 'PROCUREMENT_MANAGER', 'INDENTS', 'reject_indent', true),
  (gen_random_uuid()::text, 'PROCUREMENT_MANAGER', 'PURCHASE_ORDERS', 'view_purchase_order', true),
  (gen_random_uuid()::text, 'PROCUREMENT_MANAGER', 'PURCHASE_ORDERS', 'add_purchase_order', true),
  (gen_random_uuid()::text, 'PROCUREMENT_MANAGER', 'PURCHASE_ORDERS', 'edit_purchase_order', true),
  (gen_random_uuid()::text, 'PROCUREMENT_MANAGER', 'PURCHASE_ORDERS', 'delete_purchase_order', true),
  (gen_random_uuid()::text, 'PROCUREMENT_MANAGER', 'PURCHASE_ORDERS', 'submit_purchase_order', true),
  (gen_random_uuid()::text, 'PROCUREMENT_MANAGER', 'PURCHASE_ORDERS', 'approve_purchase_order', true),
  (gen_random_uuid()::text, 'PROCUREMENT_MANAGER', 'PURCHASE_ORDERS', 'reject_purchase_order', true),
  (gen_random_uuid()::text, 'PROCUREMENT_MANAGER', 'GRN', 'view_goods_received', true),
  (gen_random_uuid()::text, 'PROCUREMENT_MANAGER', 'GRN', 'add_goods_received', true),
  (gen_random_uuid()::text, 'PROCUREMENT_MANAGER', 'GRN', 'edit_goods_received', true),
  (gen_random_uuid()::text, 'PROCUREMENT_MANAGER', 'GRN', 'delete_goods_received', true),
  (gen_random_uuid()::text, 'PROCUREMENT_MANAGER', 'INVENTORY', 'view_inventory', true),
  (gen_random_uuid()::text, 'PROCUREMENT_MANAGER', 'INVENTORY', 'add_inventory', true),
  (gen_random_uuid()::text, 'PROCUREMENT_MANAGER', 'INVENTORY', 'edit_inventory', true),
  (gen_random_uuid()::text, 'PROCUREMENT_MANAGER', 'INVENTORY', 'delete_inventory', true),
  (gen_random_uuid()::text, 'SALES_ADMIN', 'DASHBOARD', 'view_dashboard', true),
  (gen_random_uuid()::text, 'SALES_ADMIN', 'PROPERTIES', 'view_property', true),
  (gen_random_uuid()::text, 'SALES_ADMIN', 'SALES_DASHBOARD', 'view_sales_dashboard', true),
  (gen_random_uuid()::text, 'SALES_ADMIN', 'SALES_LEADS', 'view_sales_crm', true),
  (gen_random_uuid()::text, 'SALES_ADMIN', 'SALES_LEADS', 'add_sales_crm', true),
  (gen_random_uuid()::text, 'SALES_ADMIN', 'SALES_LEADS', 'edit_sales_crm', true),
  (gen_random_uuid()::text, 'SALES_ADMIN', 'SALES_LEADS', 'delete_sales_crm', true),
  (gen_random_uuid()::text, 'SALES_ADMIN', 'PROPERTY_LEADS', 'view_property_lead', true),
  (gen_random_uuid()::text, 'SALES_ADMIN', 'PROPERTY_LEADS', 'add_property_lead', true),
  (gen_random_uuid()::text, 'SALES_ADMIN', 'PROPERTY_LEADS', 'edit_property_lead', true),
  (gen_random_uuid()::text, 'SALES_ADMIN', 'PROPERTY_LEADS', 'delete_property_lead', true),
  (gen_random_uuid()::text, 'SALES_MANAGER', 'DASHBOARD', 'view_dashboard', true),
  (gen_random_uuid()::text, 'SALES_MANAGER', 'PROPERTIES', 'view_property', true),
  (gen_random_uuid()::text, 'SALES_MANAGER', 'SALES_DASHBOARD', 'view_sales_dashboard', true),
  (gen_random_uuid()::text, 'SALES_MANAGER', 'SALES_LEADS', 'view_sales_crm', true),
  (gen_random_uuid()::text, 'SALES_MANAGER', 'SALES_LEADS', 'add_sales_crm', true),
  (gen_random_uuid()::text, 'SALES_MANAGER', 'SALES_LEADS', 'edit_sales_crm', true),
  (gen_random_uuid()::text, 'SALES_MANAGER', 'SALES_LEADS', 'delete_sales_crm', true),
  (gen_random_uuid()::text, 'SALES_MANAGER', 'PROPERTY_LEADS', 'view_property_lead', true),
  (gen_random_uuid()::text, 'SALES_MANAGER', 'PROPERTY_LEADS', 'add_property_lead', true),
  (gen_random_uuid()::text, 'SALES_MANAGER', 'PROPERTY_LEADS', 'edit_property_lead', true),
  (gen_random_uuid()::text, 'SALES_MANAGER', 'PROPERTY_LEADS', 'delete_property_lead', true),
  (gen_random_uuid()::text, 'SALES_EXECUTIVE', 'DASHBOARD', 'view_dashboard', true),
  (gen_random_uuid()::text, 'SALES_EXECUTIVE', 'SALES_LEADS', 'view_sales_crm', true),
  (gen_random_uuid()::text, 'SALES_EXECUTIVE', 'SALES_LEADS', 'add_sales_crm', true),
  (gen_random_uuid()::text, 'SALES_EXECUTIVE', 'SALES_LEADS', 'edit_sales_crm', true),
  (gen_random_uuid()::text, 'SALES_EXECUTIVE', 'SALES_LEADS', 'delete_sales_crm', true),
  (gen_random_uuid()::text, 'SALES_EXECUTIVE', 'SALES_DASHBOARD', 'view_sales_dashboard', true),
  (gen_random_uuid()::text, 'SALES_EXECUTIVE', 'PROPERTY_LEADS', 'view_property_lead', true),
  (gen_random_uuid()::text, 'HR_MANAGER', 'DASHBOARD', 'view_dashboard', true),
  (gen_random_uuid()::text, 'HR_MANAGER', 'EMPLOYEES', 'view_employee', true),
  (gen_random_uuid()::text, 'HR_MANAGER', 'EMPLOYEES', 'add_employee', true),
  (gen_random_uuid()::text, 'HR_MANAGER', 'EMPLOYEES', 'edit_employee', true),
  (gen_random_uuid()::text, 'HR_MANAGER', 'EMPLOYEES', 'delete_employee', true),
  (gen_random_uuid()::text, 'HR_MANAGER', 'EMPLOYEES', 'approve_employee', true),
  (gen_random_uuid()::text, 'HR_MANAGER', 'EMPLOYEES', 'reject_employee', true),
  (gen_random_uuid()::text, 'HR_MANAGER', 'EMPLOYEES', 'export_employee', true),
  (gen_random_uuid()::text, 'HR_MANAGER', 'RECRUITMENT', 'view_recruitment', true),
  (gen_random_uuid()::text, 'HR_MANAGER', 'RECRUITMENT', 'add_recruitment', true),
  (gen_random_uuid()::text, 'HR_MANAGER', 'RECRUITMENT', 'edit_recruitment', true),
  (gen_random_uuid()::text, 'HR_MANAGER', 'RECRUITMENT', 'delete_recruitment', true),
  (gen_random_uuid()::text, 'HR_MANAGER', 'RECRUITMENT', 'approve_recruitment', true),
  (gen_random_uuid()::text, 'HR_MANAGER', 'RECRUITMENT', 'reject_recruitment', true),
  (gen_random_uuid()::text, 'HR_MANAGER', 'LND', 'view_learning_development', true),
  (gen_random_uuid()::text, 'HR_MANAGER', 'LND', 'add_learning_development', true),
  (gen_random_uuid()::text, 'HR_MANAGER', 'LND', 'edit_learning_development', true),
  (gen_random_uuid()::text, 'HR_MANAGER', 'LND', 'delete_learning_development', true),
  (gen_random_uuid()::text, 'HR_MANAGER', 'USERS', 'view_user', true),
  (gen_random_uuid()::text, 'HR_MANAGER', 'USERS', 'add_user', true),
  (gen_random_uuid()::text, 'HR_MANAGER', 'USERS', 'edit_user', true),
  (gen_random_uuid()::text, 'HR_MANAGER', 'USERS', 'delete_user', true),
  (gen_random_uuid()::text, 'HR_MANAGER', 'USERS', 'configure_user', true),
  (gen_random_uuid()::text, 'HR_MANAGER', 'SETTINGS', 'view_setting', true),
  (gen_random_uuid()::text, 'HR_MANAGER', 'COMPLAINT_ROUTING', 'view_routing_sla', true);

COMMIT;

-- ── After this file ─────────────────────────────────────────────────────────
-- `drizzle-kit push` has nothing left to do for roles. Verify with:
--   SELECT key, label, anchor_level FROM roles ORDER BY rank DESC, key;
--   SELECT role_key, count(*) FROM role_functionalities GROUP BY 1 ORDER BY 1;
